(()=>{'use strict';
const KEY='aa-companion7-state-v3',IMG_DB='chronologia-local-companion-v1',IMG_STORE='images';
const FALLBACK='https://shop.hololivepro.com/cdn/shop/files/hololive_startingvoice_SakamataChloe_banner_top.png?v=1687758072';
const C={version:'7.4.1',state:{visible:true,x:null,y:null,scale:1,expression:'neutral',mouthOpen:0,mouthForm:0,eyeL:1,eyeR:1,gazeX:0,gazeY:0,headX:0,headY:0,headZ:0,breath:0,cutout:true,motion:true},host:null,canvas:null,ctx:null,img:null,renderable:null,imgURL:null,audioCtx:null,analyser:null,lastBlink:0,nextBlink:performance.now()+2500,blinkPhase:0,source:'none',reaction:null,particles:[],lastT:0};
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');Object.assign(C.state,s);if(typeof C.state.cutout!=='boolean')C.state.cutout=true;if(typeof C.state.motion!=='boolean')C.state.motion=true;if(!Number.isFinite(+C.state.scale))C.state.scale=1}catch(_){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({visible:C.state.visible,x:C.state.x,y:C.state.y,scale:C.state.scale,expression:C.state.expression,cutout:C.state.cutout,motion:C.state.motion}))}catch(_){}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(IMG_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(IMG_STORE))r.result.createObjectStore(IMG_STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function blobFromFile(file){return file instanceof Blob?file:new Blob([file],{type:file?.type||'image/png'})}
async function saveTexture(file){const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(IMG_STORE,'readwrite');tx.objectStore(IMG_STORE).put(blobFromFile(file),'01_normal.png');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();return loadNeutral()}
async function resetTexture(){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction(IMG_STORE,'readwrite');tx.objectStore(IMG_STORE).delete('01_normal.png');tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch(_){}return loadNeutral()}
function rgbStats(r,g,b){const mx=Math.max(r,g,b)/255,mn=Math.min(r,g,b)/255,l=(mx+mn)/2,d=mx-mn,s=d===0?0:d/(1-Math.abs(2*l-1));return{l,s}}
function makeCutout(im){if(!C.state.cutout)return im;try{const max=460,ratio=Math.min(1,max/Math.max(im.naturalWidth,im.naturalHeight)),w=Math.max(2,Math.round(im.naturalWidth*ratio)),h=Math.max(2,Math.round(im.naturalHeight*ratio)),cv=document.createElement('canvas');cv.width=w;cv.height=h;const x=cv.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,w,h);const d=x.getImageData(0,0,w,h),a=d.data,n=w*h,seen=new Uint8Array(n),q=new Int32Array(n),corners=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]].map(([cx,cy])=>{const i=(cy*w+cx)*4,r=a[i],g=a[i+1],b=a[i+2],st=rgbStats(r,g,b);return{r,g,b,use:a[i+3]<80||st.l>.48}});
const candidate=p=>{const i=p*4,al=a[i+3];if(al<50)return true;const r=a[i],g=a[i+1],b=a[i+2],st=rgbStats(r,g,b);if(st.l>.79&&st.s<.42)return true;if(b>168&&g>150&&b>r+8&&st.l>.58)return true;for(const c of corners){if(!c.use)continue;const dr=r-c.r,dg=g-c.g,db=b-c.b;if(dr*dr+dg*dg+db*db<4200&&st.l>.42)return true}return false};let head=0,tail=0;const push=p=>{if(p<0||p>=n||seen[p]||!candidate(p))return;seen[p]=1;q[tail++]=p};for(let xx=0;xx<w;xx++){push(xx);push((h-1)*w+xx)}for(let yy=0;yy<h;yy++){push(yy*w);push(yy*w+w-1)}while(head<tail){const p=q[head++],px=p%w,py=(p/w)|0;if(px)push(p-1);if(px<w-1)push(p+1);if(py)push(p-w);if(py<h-1)push(p+w)}for(let p=0;p<n;p++)if(seen[p])a[p*4+3]=0;
// Keep the largest visible connected component. This also removes detached logos/text.
const vis=new Uint8Array(n),qq=new Int32Array(n);let best=[],bestN=0;for(let p=0;p<n;p++){if(vis[p]||a[p*4+3]<24)continue;let H=0,T=0;qq[T++]=p;vis[p]=1;const comp=[];while(H<T){const u=qq[H++];comp.push(u);const ux=u%w,uy=(u/w)|0;const add=v=>{if(v>=0&&v<n&&!vis[v]&&a[v*4+3]>=24){vis[v]=1;qq[T++]=v}};if(ux)add(u-1);if(ux<w-1)add(u+1);if(uy)add(u-w);if(uy<h-1)add(u+w)}if(comp.length>bestN){bestN=comp.length;best=comp}}if(bestN>300){const keep=new Uint8Array(n);for(const p of best)keep[p]=1;for(let p=0;p<n;p++)if(a[p*4+3]>=24&&!keep[p])a[p*4+3]=0}
x.putImageData(d,0,0);return cv}catch(e){console.warn('Companion7 cutout skipped',e);return im}}
function setImage(src,source){return new Promise(ok=>{const im=new Image();im.decoding='async';if(/^https?:/i.test(src))im.crossOrigin='anonymous';im.onload=()=>{C.img=im;C.source=source;C.renderable=makeCutout(im);C.host?.classList.add('hasTexture');document.dispatchEvent(new CustomEvent('companion7:texture',{detail:{loaded:true,source,cutout:C.state.cutout}}));ok(true)};im.onerror=()=>ok(false);im.src=src})}
async function loadNeutral(){let local=null;try{const d=await openDB();local=await new Promise(ok=>{const tx=d.transaction(IMG_STORE,'readonly'),r=tx.objectStore(IMG_STORE).get('01_normal.png');r.onsuccess=()=>ok(r.result||null);r.onerror=()=>ok(null)});d.close()}catch(_){}if(local){if(C.imgURL)URL.revokeObjectURL(C.imgURL);C.imgURL=URL.createObjectURL(local);if(await setImage(C.imgURL,'indexeddb'))return true}if(await setImage(FALLBACK,'official-fallback'))return true;C.source='none';C.renderable=null;document.dispatchEvent(new CustomEvent('companion7:texture',{detail:{loaded:false,source:'none'}}));return false}
function css(){if(document.getElementById('companion7-css'))return;const s=document.createElement('style');s.id='companion7-css';s.textContent=`#companion7{position:fixed;right:8px;bottom:calc(82px + env(safe-area-inset-bottom,0px));width:138px;height:170px;z-index:58;touch-action:none;user-select:none;overflow:visible;background:transparent!important;border:0!important;filter:drop-shadow(0 9px 12px rgba(16,24,40,.20));transition:opacity .18s,filter .2s}#companion7[data-hidden=true]{opacity:0;pointer-events:none}#companion7 canvas{width:100%;height:100%;display:block;background:transparent!important}#companion7 .c7badge{position:absolute;right:-2px;bottom:1px;background:rgba(16,24,40,.90);color:#fff;border:1px solid rgba(255,255,255,.8);border-radius:999px;padding:4px 7px;font:800 10px -apple-system,BlinkMacSystemFont,sans-serif;box-shadow:0 4px 12px rgba(0,0,0,.18)}#companion7.c7-react{filter:drop-shadow(0 10px 17px rgba(36,88,211,.32))}@media(max-width:390px){#companion7{width:126px;height:156px;right:5px;bottom:calc(80px + env(safe-area-inset-bottom,0px))}}@media(prefers-reduced-motion:reduce){#companion7{transition:none}}`;document.head.appendChild(s)}
function clampPos(){if(!C.host||C.state.x==null)return;const r=C.host.getBoundingClientRect(),pad=4;C.state.x=Math.max(pad,Math.min(innerWidth-r.width-pad,C.state.x));C.state.y=Math.max(pad,Math.min(innerHeight-r.height-72-pad,C.state.y));C.host.style.left=C.state.x+'px';C.host.style.top=C.state.y+'px';C.host.style.right='auto';C.host.style.bottom='auto'}
function spark(type){const good=/correct|streak|complete|tap/.test(type),count=type==='complete'?16:type==='streak'?10:good?6:3;for(let i=0;i<count;i++)C.particles.push({x:210+(Math.random()-.5)*250,y:250+(Math.random()-.5)*200,vx:(Math.random()-.5)*1.8,vy:-.6-Math.random()*1.6,life:1,size:3+Math.random()*6,good})}
function react(type){const now=performance.now();C.reaction={type,start:now,until:now+(type==='complete'?1200:650)};spark(type);C.host?.classList.add('c7-react');setTimeout(()=>C.host?.classList.remove('c7-react'),700)}
function mount(){if(C.host)return;css();document.getElementById('aaPet')?.remove();document.getElementById('aaPetSheet')?.remove();const h=document.createElement('div');h.id='companion7';h.innerHTML='<canvas width="420" height="520" aria-label="学習相棒"></canvas><span class="c7badge">相棒</span>';document.body.appendChild(h);C.host=h;C.canvas=h.querySelector('canvas');C.ctx=C.canvas.getContext('2d',{alpha:true});h.dataset.hidden=!C.state.visible;let sx,sy,bx,by,drag=false,moved=false;h.addEventListener('pointerdown',e=>{drag=true;moved=false;sx=e.clientX;sy=e.clientY;const r=h.getBoundingClientRect();bx=r.left;by=r.top;h.setPointerCapture?.(e.pointerId)});h.addEventListener('pointermove',e=>{const r=h.getBoundingClientRect();C.state.gazeX=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width/2)));C.state.gazeY=Math.max(-1,Math.min(1,(e.clientY-r.top-r.height/2)/(r.height/2)));if(!drag)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.hypot(dx,dy)>6)moved=true;C.state.x=bx+dx;C.state.y=by+dy;clampPos()});h.addEventListener('pointerup',()=>{drag=false;if(!moved){event('tap')}save()});h.addEventListener('pointercancel',()=>{drag=false;save()});if(C.state.x!=null)clampPos();addEventListener('resize',clampPos,{passive:true});loadNeutral();requestAnimationFrame(loop)}
function blink(t){if(t<C.nextBlink&&C.blinkPhase===0)return 1;if(C.blinkPhase===0){C.lastBlink=t;C.blinkPhase=1}const d=t-C.lastBlink;let v=1;if(d<75)v=1-d/75;else if(d<110)v=0;else if(d<220)v=(d-110)/110;else{C.blinkPhase=0;C.nextBlink=t+2200+Math.random()*3800}return Math.max(0,Math.min(1,v))}
function drawParticles(dt){const x=C.ctx;for(let i=C.particles.length-1;i>=0;i--){const p=C.particles[i];p.x+=p.vx*dt*.06;p.y+=p.vy*dt*.06;p.vy+=.018*dt*.06;p.life-=dt/850;if(p.life<=0){C.particles.splice(i,1);continue}x.save();x.globalAlpha=Math.max(0,p.life);x.translate(p.x,p.y);x.rotate((1-p.life)*2.5);x.fillStyle=p.good?'rgba(255,214,86,.95)':'rgba(126,146,180,.8)';const s=p.size;x.beginPath();x.moveTo(0,-s);x.lineTo(s*.35,-s*.35);x.lineTo(s,0);x.lineTo(s*.35,s*.35);x.lineTo(0,s);x.lineTo(-s*.35,s*.35);x.lineTo(-s,0);x.lineTo(-s*.35,-s*.35);x.closePath();x.fill();x.restore()}}
function draw(t){const x=C.ctx,w=C.canvas.width,h=C.canvas.height,dt=Math.min(40,Math.max(0,t-(C.lastT||t)));C.lastT=t;x.clearRect(0,0,w,h);const mot=C.state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;C.state.breath=mot?(Math.sin(t/760)+1)/2:.5;const e=blink(t);C.state.eyeL=e;C.state.eyeR=e;let floatY=mot?Math.sin(t/760)*3:0,rot=mot?Math.sin(t/3100+.4)*.010:0,pulse=1+(mot?Math.sin(t/760)*.004:0),shake=0;if(C.reaction&&t<C.reaction.until){const p=(t-C.reaction.start)/(C.reaction.until-C.reaction.start),decay=1-p;if(C.reaction.type==='wrong')shake=Math.sin(p*42)*6*decay;if(/correct|streak|complete|tap/.test(C.reaction.type))pulse+=Math.sin(Math.min(1,p)*Math.PI)*(.045+(C.reaction.type==='complete'?.035:0))}else C.reaction=null;C.state.headZ=rot;C.state.headX=C.state.gazeX*.018;C.state.headY=C.state.gazeY*.012;const r=C.renderable||C.img;if(r){const rw=r.width||r.naturalWidth,rh=r.height||r.naturalHeight;if(rw&&rh){x.save();x.translate(w/2+shake+(mot?C.state.gazeX*2:0),h/2+floatY+(mot?C.state.gazeY*1.2:0));x.rotate(rot+C.state.gazeX*.006);const base=Math.min(w/rw,h/rh)*1.03*Math.max(.72,Math.min(1.45,+C.state.scale||1));x.scale(base*pulse,base*pulse);x.drawImage(r,-rw/2,-rh/2,rw,rh);x.restore()}}else{x.fillStyle='rgba(23,32,51,.75)';x.textAlign='center';x.font='800 18px -apple-system';x.fillText('相棒',w/2,h/2-4);x.font='12px -apple-system';x.fillStyle='#667085';x.fillText('画像を再取得中',w/2,h/2+20)}drawParticles(dt)}
function loop(t){draw(t);requestAnimationFrame(loop)}
function expression(name){C.state.expression=name;save();document.dispatchEvent(new CustomEvent('companion7:expression',{detail:{name}}))}
function event(type){const m={correct:'joy',wrong:'annoyed',streak:'proud',hard:'serious',idle:'neutral',complete:'laugh',tap:'joy'};expression(m[type]||'neutral');react(type)}
async function bindAudio(el){if(!el||el.__c7bound)return;el.__c7bound=true;try{C.audioCtx=C.audioCtx||new (window.AudioContext||window.webkitAudioContext)();C.analyser=C.audioCtx.createAnalyser();C.analyser.fftSize=512;const src=C.audioCtx.createMediaElementSource(el);src.connect(C.analyser);C.analyser.connect(C.audioCtx.destination);const arr=new Uint8Array(C.analyser.frequencyBinCount);(function lip(){if(!C.analyser)return;C.analyser.getByteFrequencyData(arr);let s=0,n=0;for(let i=2;i<45;i++){s+=arr[i];n++}const target=Math.min(1,(s/Math.max(1,n))/105);C.state.mouthOpen=C.state.mouthOpen*.58+target*.42;requestAnimationFrame(lip)})()}catch(e){console.warn('Companion7 audio bind',e)}}
function show(v=true){C.state.visible=!!v;if(C.host)C.host.dataset.hidden=!v;save()}
function setCutout(v=true){C.state.cutout=!!v;save();if(C.img){C.renderable=makeCutout(C.img);document.dispatchEvent(new CustomEvent('companion7:cutout',{detail:{enabled:C.state.cutout}}))}}
function setMotion(v=true){C.state.motion=!!v;save()}
function setScale(v=1){C.state.scale=Math.max(.72,Math.min(1.45,+v||1));save()}
loadState();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();window.Companion7={version:C.version,state:C.state,expression,event,bindAudio,show,save,reloadTexture:loadNeutral,setTextureFile:saveTexture,resetTexture,setCutout,setMotion,setScale,get source(){return C.source}}})();