(()=>{'use strict';
if(window.__AA_HEADER_MENU_V1__)return;
window.__AA_HEADER_MENU_V1__={version:'1.1.0'};
const STYLE_ID='aa-header-menu-v1-style';
const OVERLAY_ID='aaHeaderMenuOverlay';
const PANEL_ID='aaHeaderMenuPanel';
const TOGGLE_ID='aaHeaderMenuToggle';
let raf=0,lastFocus=null,lastTouchActionAt=0;
function injectStyle(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.topBtns>[data-aa-menu-source="1"]{display:none!important}#aaStudyTimerFab,#kokugoChronologiaQuickLink{display:none!important}
#${TOGGLE_ID}{display:inline-grid;place-items:center;min-width:42px;min-height:40px;padding:7px 10px;font-size:22px;line-height:1;letter-spacing:0;touch-action:manipulation}
#${OVERLAY_ID}{position:fixed;inset:0;z-index:2147483000;background:rgba(7,12,22,.55);opacity:0;pointer-events:none;transition:opacity .18s ease;isolation:isolate}
#${OVERLAY_ID}.open{opacity:1;pointer-events:auto!important}
#${PANEL_ID}{position:absolute;z-index:1;top:0;right:0;height:100%;width:min(340px,88vw);background:#10254a;color:#f7f9ff;box-shadow:-18px 0 48px rgba(0,0,0,.28);transform:translateX(104%);transition:transform .2s ease;overflow:auto;-webkit-overflow-scrolling:touch;overscroll-behavior:contain;pointer-events:auto!important;padding:calc(14px + env(safe-area-inset-top,0px)) 14px calc(18px + env(safe-area-inset-bottom,0px));font-family:-apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic UI","Yu Gothic",sans-serif}
#${OVERLAY_ID}.open #${PANEL_ID}{transform:translateX(0)}.aaMenuHead{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:2px 2px 12px;border-bottom:1px solid rgba(255,255,255,.12)}.aaMenuHead strong{font-size:16px}.aaMenuClose{position:relative;z-index:2;border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.05);color:inherit;border-radius:10px;min-width:40px;min-height:40px;font-size:20px;font-weight:900;cursor:pointer;pointer-events:auto!important;touch-action:manipulation}
.aaMenuList{display:grid;gap:8px;padding:14px 0;pointer-events:auto!important}.aaMenuItem{position:relative;z-index:2;width:100%;display:grid;grid-template-columns:34px 1fr auto;align-items:center;gap:10px;text-align:left;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.05);color:#f7f9ff;border-radius:14px;padding:12px;min-height:54px;text-decoration:none;font:inherit;cursor:pointer;pointer-events:auto!important;touch-action:manipulation;-webkit-user-select:none;user-select:none}.aaMenuItem>*{pointer-events:none}.aaMenuItem:active{transform:translateY(1px);background:rgba(255,255,255,.09)}.aaMenuIcon{font-size:19px;text-align:center}.aaMenuText{min-width:0}.aaMenuText b{display:block;font-size:13px}.aaMenuText small{display:block;margin-top:2px;color:rgba(235,240,255,.62);font-size:10px;line-height:1.35}.aaMenuArrow{color:rgba(235,240,255,.45);font-weight:900}.aaMenuFoot{padding-top:10px;border-top:1px solid rgba(255,255,255,.10);font-size:10px;line-height:1.5;color:rgba(235,240,255,.55)}
@media(prefers-reduced-motion:reduce){#${OVERLAY_ID},#${PANEL_ID}{transition:none!important}}`;document.head.appendChild(s)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function source(sel){return document.querySelector(sel)}
function knownItems(){const theme=source('.topBtns [data-action="theme"]'),settings=source('.topBtns [data-route="settings"]');return [{key:'theme',icon:'◐',label:'表示テーマ',sub:theme?`${(theme.textContent||'').trim()}モードへ切替`:'明るさを切替',source:theme},{key:'settings',icon:'⚙',label:'設定',sub:'学習範囲・バックアップ',source:settings}]}
function markHeaderSources(){const box=document.querySelector('.topBtns');if(!box)return null;[...box.children].forEach(el=>{if(el.id!==TOGGLE_ID)el.dataset.aaMenuSource='1'});let toggle=box.querySelector('#'+TOGGLE_ID);if(!toggle){toggle=document.createElement('button');toggle.type='button';toggle.id=TOGGLE_ID;toggle.className='iconBtn';toggle.setAttribute('aria-label','メニューを開く');toggle.setAttribute('aria-haspopup','dialog');toggle.setAttribute('aria-controls',PANEL_ID);toggle.setAttribute('aria-expanded','false');toggle.textContent='☰';box.appendChild(toggle)}return toggle}
function ensureOverlay(){let o=document.getElementById(OVERLAY_ID);if(o)return o;o=document.createElement('div');o.id=OVERLAY_ID;o.setAttribute('aria-hidden','true');o.innerHTML=`<aside id="${PANEL_ID}" role="dialog" aria-modal="true" aria-label="アプリメニュー"><div class="aaMenuHead"><strong>メニュー</strong><button type="button" class="aaMenuClose" aria-label="メニューを閉じる">×</button></div><div class="aaMenuList"></div><div class="aaMenuFoot">よく使う機能は下部ナビに集約しています。</div></aside>`;document.body.appendChild(o);return o}
function renderItems(){const o=ensureOverlay(),list=o.querySelector('.aaMenuList');if(!list)return;list.innerHTML=knownItems().map(x=>`<button type="button" class="aaMenuItem" data-aa-menu-key="${x.key}" aria-label="${esc(x.label)}"><span class="aaMenuIcon">${x.icon}</span><span class="aaMenuText"><b>${esc(x.label)}</b><small>${esc(x.sub)}</small></span><span class="aaMenuArrow">›</span></button>`).join('')}
function openMenu(){const o=ensureOverlay();renderItems();lastFocus=document.activeElement;o.classList.add('open');o.setAttribute('aria-hidden','false');document.getElementById(TOGGLE_ID)?.setAttribute('aria-expanded','true')}
function closeMenu({restoreFocus=true}={}){const o=document.getElementById(OVERLAY_ID);if(!o)return;o.classList.remove('open');o.setAttribute('aria-hidden','true');document.getElementById(TOGGLE_ID)?.setAttribute('aria-expanded','false');if(restoreFocus&&lastFocus?.isConnected)setTimeout(()=>lastFocus.focus?.(),0)}
function activate(key){const item=knownItems().find(x=>x.key===key);if(!item)return;closeMenu({restoreFocus:false});setTimeout(()=>{const el=item.source;if(el){try{el.click()}catch(_){}}},0)}
function menuTarget(target){if(!(target instanceof Element))return null;return target.closest('#'+TOGGLE_ID+',.aaMenuClose,[data-aa-menu-key],#'+OVERLAY_ID)}
function handleMenuEvent(e,isTouch=false){const target=menuTarget(e.target);if(!target)return false;if(target.id===OVERLAY_ID&&e.target!==target)return false;if(!isTouch&&Date.now()-lastTouchActionAt<700){e.preventDefault();e.stopPropagation();return true}if(isTouch)lastTouchActionAt=Date.now();e.preventDefault();e.stopPropagation();if(target.id===TOGGLE_ID){openMenu();return true}if(target.classList.contains('aaMenuClose')){closeMenu();return true}if(target.hasAttribute('data-aa-menu-key')){activate(target.dataset.aaMenuKey);return true}if(target.id===OVERLAY_ID){closeMenu();return true}return false}
function apply(){raf=0;injectStyle();markHeaderSources();ensureOverlay()}
function queue(){if(raf)return;raf=requestAnimationFrame(apply)}
function bind(){document.addEventListener('click',e=>handleMenuEvent(e,false),true);if('PointerEvent'in window){document.addEventListener('pointerup',e=>{if(e.pointerType==='touch'||e.pointerType==='pen')handleMenuEvent(e,true)},true)}else document.addEventListener('touchend',e=>handleMenuEvent(e,true),{capture:true,passive:false});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById(OVERLAY_ID)?.classList.contains('open')){e.preventDefault();closeMenu()}});new MutationObserver(queue).observe(document.documentElement,{childList:true,subtree:true});addEventListener('hashchange',queue);addEventListener('popstate',queue);queue();setTimeout(queue,300);setTimeout(queue,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();