(()=>{'use strict';
if(window.__AA_REVIEW_PAGE_V1__)return;window.__AA_REVIEW_PAGE_V1__=true;
const PROGRESS_KEY='asahi_review_progress_v1';
const reviewUI={subject:'全部',status:'要復習',query:'',revealed:new Set(),returnRoute:'home'};
function readLegacyProgress(){try{const x=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');return x&&typeof x==='object'?{done:x.done&&typeof x.done==='object'?x.done:{},seen:x.seen&&typeof x.seen==='object'?x.seen:{}}:{done:{},seen:{}}}catch(_){return {done:{},seen:{}}}}
let progress=readLegacyProgress();
function E(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function bank(){return Array.isArray(window.AA_REVIEW_BANK)?window.AA_REVIEW_BANK:[]}
function done(id){return !!progress.done[id]}
function subjects(){return ['全部',...new Set(bank().map(x=>x.subject).filter(Boolean))]}
function filtered(){const q=reviewUI.query.trim().toLowerCase();return bank().filter(x=>{
  if(reviewUI.subject!=='全部'&&x.subject!==reviewUI.subject)return false;
  if(reviewUI.status==='要復習'&&done(x.id))return false;
  if(reviewUI.status==='復習済み'&&!done(x.id))return false;
  if(!q)return true;
  return [x.subject,x.unit,x.title,x.question,x.answer,x.why,x.memory,...(x.tags||[]),...(x.examples||[])].join(' ').toLowerCase().includes(q)
})}
function styles(){return `<style id="aa-review-style">
.aaReviewHero{background:linear-gradient(145deg,var(--card),var(--blue2));border-color:color-mix(in srgb,var(--blue) 22%,var(--line))}.aaReviewStats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-top:14px}.aaReviewStat{padding:10px;border:1px solid var(--line);border-radius:13px;background:var(--card);text-align:center}.aaReviewStat b{display:block;font-size:20px}.aaReviewStat span{font-size:10px;color:var(--sub)}.aaReviewSearch{margin-top:12px}.aaReviewFilters{display:flex;gap:7px;overflow:auto;padding:10px 1px 3px;scrollbar-width:none}.aaReviewFilters::-webkit-scrollbar{display:none}.aaReviewFilter{white-space:nowrap;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:999px;padding:8px 11px;font-size:12px;font-weight:800}.aaReviewFilter.active{background:var(--blue2);color:var(--blue);border-color:var(--blue)}.aaReviewCard{margin-top:12px}.aaReviewMeta{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.aaReviewQuestion{font-size:17px;line-height:1.7;font-weight:800;margin:12px 0}.aaReviewAnswer{margin-top:10px;padding:13px;border-radius:13px;background:var(--green2);border:1px solid color-mix(in srgb,var(--green) 22%,var(--line));line-height:1.75;font-size:14px}.aaReviewWhy{margin-top:10px;padding:12px;border-left:4px solid var(--blue);border-radius:10px;background:var(--blue2);font-size:13px;line-height:1.7}.aaReviewMemory{margin-top:10px;padding:11px;border-radius:11px;background:var(--amber2);font-size:13px;line-height:1.6}.aaReviewExamples{margin:10px 0 0;padding-left:20px;line-height:1.8;font-size:13px}.aaReviewEmpty{text-align:center;color:var(--sub);padding:32px 10px}.aaReviewDone{opacity:.72}.aaReviewDone .aaReviewQuestion{text-decoration:line-through;text-decoration-thickness:1px}.aaReviewHeaderBtn{display:inline-flex;align-items:center;text-decoration:none}@media(max-width:520px){.aaReviewStats{grid-template-columns:repeat(3,1fr)}.aaReviewStat b{font-size:17px}}
</style>`}
function cardHTML(x){const isDone=done(x.id),revealed=reviewUI.revealed.has(x.id);return `<section class="card aaReviewCard ${isDone?'aaReviewDone':''}" data-review-card="${E(x.id)}"><div class="aaReviewMeta"><span class="chip">${E(x.subject)}</span>${x.unit?`<span class="chip">${E(x.unit)}</span>`:''}<span class="chip ${isDone?'good':'warn'}">${isDone?'復習済み':'要復習'}</span><span class="tiny">${E(x.createdAt||'')}</span></div><h3 class="h3" style="margin-top:10px">${E(x.title)}</h3><div class="aaReviewQuestion">${E(x.question)}</div>${revealed?`<div class="aaReviewAnswer"><b>答え</b><br>${E(x.answer)}</div>${x.why?`<div class="aaReviewWhy"><b>なぜ？</b><br>${E(x.why)}</div>`:''}${x.memory?`<div class="aaReviewMemory"><b>覚え方：</b> ${E(x.memory)}</div>`:''}${x.examples?.length?`<ul class="aaReviewExamples">${x.examples.map(v=>`<li>${E(v)}</li>`).join('')}</ul>`:''}`:''}<div class="sp12"></div><div class="actions"><button class="btn ${revealed?'ghost':'primary'}" data-review-reveal="${E(x.id)}">${revealed?'答えを隠す':'答えを見る'}</button><button class="btn ${isDone?'ghost':'good'}" data-review-done="${E(x.id)}">${isDone?'もう一度復習する':'覚えた'}</button></div></section>`}
function pageHTML(){const all=bank(),completed=all.filter(x=>done(x.id)).length,remaining=all.length-completed,rows=filtered();return `${styles()}<header class="top"><div class="toprow"><div class="brand"><div class="mark">復</div><div><h1>復習ノート</h1><p>ChatGPTで指定した内容をここに蓄積</p></div></div><div class="topBtns"><button class="iconBtn" data-review-exit>戻る</button></div></div></header><main><section class="card aaReviewHero"><div class="eyebrow">PERSONAL REVIEW</div><h2 class="h2">あとで必ず見直すページ</h2><p class="sub">「これ復習に入れて」と指定した内容を、答えを隠した状態から思い出して確認できます。アプリ更新や項目追加をしても「覚えた」状態は残り、Learning OSのJSONバックアップにも含まれます。</p><div class="aaReviewStats"><div class="aaReviewStat"><b>${all.length}</b><span>登録</span></div><div class="aaReviewStat"><b>${remaining}</b><span>要復習</span></div><div class="aaReviewStat"><b>${completed}</b><span>復習済み</span></div></div><div class="aaReviewSearch"><input type="text" inputmode="search" autocomplete="off" placeholder="復習項目を検索" value="${E(reviewUI.query)}" data-review-search></div><div class="aaReviewFilters">${['要復習','全部','復習済み'].map(s=>`<button class="aaReviewFilter ${reviewUI.status===s?'active':''}" data-review-status="${s}">${s}</button>`).join('')}</div><div class="aaReviewFilters">${subjects().map(s=>`<button class="aaReviewFilter ${reviewUI.subject===s?'active':''}" data-review-subject="${E(s)}">${E(s)}</button>`).join('')}</div></section><div id="aaReviewList">${rows.length?rows.slice().reverse().map(cardHTML).join(''):'<div class="card aaReviewEmpty" style="margin-top:12px">条件に合う復習項目はありません。</div>'}</div></main>`}
function renderReview(){document.documentElement.dataset.theme=state.theme;const root=document.getElementById('app');if(root)root.innerHTML=pageHTML();try{pauseTicker()}catch(_){};document.title='復習ノート｜旭丘AA Learning OS'}
function injectButton(){const box=document.querySelector('.topBtns');if(!box||box.querySelector('[data-review-open]')||state.route==='review')return;const old=box.querySelector('[data-aa-review]');if(old)old.remove();const b=document.createElement('button');b.className='iconBtn aaReviewHeaderBtn';b.type='button';b.dataset.reviewOpen='1';b.textContent='復習';box.prepend(b)}
function setReviewURL(on){try{const u=new URL(location.href);if(on)u.searchParams.set('review','1');else u.searchParams.delete('review');history.replaceState(null,'',u.pathname+(u.search?u.search:'')+u.hash)}catch(_){}}
function writeProgress(){state.reviewProgress=progress;try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress))}catch(_){};try{save()}catch(_){}}
function openReview(){reviewUI.returnRoute=state.route==='review'?'home':state.route;if(state.route==='study'&&state.session?.active){try{pauseSessionClock()}catch(_){}}state.lastRoute=state.route;state.route='review';setReviewURL(true);try{save()}catch(_){};render();window.scrollTo(0,0)}
function closeReview(){setReviewURL(false);const target=reviewUI.returnRoute&&reviewUI.returnRoute!=='review'?reviewUI.returnRoute:'home';if(target==='study'&&state.session?.active){state.route='study';try{resumeSessionClock()}catch(_){};try{save()}catch(_){};document.title='旭丘AA Learning OS｜PWA完全版';render();return}document.title='旭丘AA Learning OS｜PWA完全版';setRoute(target)}
function refreshList(){const list=document.getElementById('aaReviewList');if(list){const rows=filtered();list.innerHTML=rows.length?rows.slice().reverse().map(cardHTML).join(''):'<div class="card aaReviewEmpty" style="margin-top:12px">条件に合う復習項目はありません。</div>'}const stats=document.querySelectorAll('.aaReviewStat b');if(stats.length>=3){const all=bank(),completed=all.filter(x=>done(x.id)).length;stats[0].textContent=all.length;stats[1].textContent=all.length-completed;stats[2].textContent=completed}}
if(typeof render!=='function'||typeof setRoute!=='function'||typeof state==='undefined')return;
if(state.reviewProgress&&typeof state.reviewProgress==='object')progress={done:state.reviewProgress.done&&typeof state.reviewProgress.done==='object'?state.reviewProgress.done:{},seen:state.reviewProgress.seen&&typeof state.reviewProgress.seen==='object'?state.reviewProgress.seen:{}};else state.reviewProgress=progress;
const baseMergeState=typeof mergeState==='function'?mergeState:null;
if(baseMergeState)mergeState=function(incoming){const incomingReview=incoming?.reviewProgress&&typeof incoming.reviewProgress==='object'?incoming.reviewProgress:null;const out=baseMergeState(incoming);if(incomingReview){const current=out.reviewProgress&&typeof out.reviewProgress==='object'?out.reviewProgress:{done:{},seen:{}};const mergeTimes=(a,b)=>{const o={...(a||{})};for(const [k,v] of Object.entries(b||{}))if(!o[k]||Number(v)>Number(o[k]))o[k]=v;return o};out.reviewProgress={done:mergeTimes(current.done,incomingReview.done),seen:mergeTimes(current.seen,incomingReview.seen)}}return out};
const baseRender=render;
render=function(){if(state.route==='review'){renderReview();return}document.title='旭丘AA Learning OS｜PWA完全版';baseRender();setTimeout(injectButton,0)};
document.addEventListener('click',e=>{
 const open=e.target.closest('[data-review-open]');if(open){e.preventDefault();e.stopImmediatePropagation();openReview();return}
 const exit=e.target.closest('[data-review-exit]');if(exit){e.preventDefault();e.stopImmediatePropagation();closeReview();return}
 const reveal=e.target.closest('[data-review-reveal]');if(reveal){e.preventDefault();e.stopImmediatePropagation();const id=reveal.dataset.reviewReveal;if(reviewUI.revealed.has(id))reviewUI.revealed.delete(id);else{reviewUI.revealed.add(id);progress.seen[id]=Date.now();writeProgress()}refreshList();return}
 const mark=e.target.closest('[data-review-done]');if(mark){e.preventDefault();e.stopImmediatePropagation();const id=mark.dataset.reviewDone;if(done(id))delete progress.done[id];else progress.done[id]=Date.now();writeProgress();refreshList();return}
 const status=e.target.closest('[data-review-status]');if(status){e.preventDefault();e.stopImmediatePropagation();reviewUI.status=status.dataset.reviewStatus;renderReview();return}
 const subject=e.target.closest('[data-review-subject]');if(subject){e.preventDefault();e.stopImmediatePropagation();reviewUI.subject=subject.dataset.reviewSubject;renderReview();return}
},true);
document.addEventListener('input',e=>{const x=e.target.closest?.('[data-review-search]');if(!x)return;reviewUI.query=x.value;refreshList()},true);
new MutationObserver(()=>{if(state.route!=='review')injectButton()}).observe(document.documentElement,{subtree:true,childList:true});
const direct=new URL(location.href).searchParams.get('review')==='1';if(direct){reviewUI.returnRoute='home';state.route='review';try{save()}catch(_){};render()}else injectButton();
window.AA_REVIEW_API={open:openReview,close:closeReview,getItems:()=>bank().slice(),getProgress:()=>JSON.parse(JSON.stringify(progress))};
})();