'use strict';
const VERSION='2.5.166-quality2-chronologia1000-kokugo-direct-ja';
const CACHE_NAME=`asahigaoka-aa-os-${VERSION}`;
const BASE=self.registration.scope;
const url=(path)=>new URL(path,BASE).href;
const CORE=[url('study-list-nav-v1.js'),url('./'),url('index.html'),url('vocabulary.html'),url('vocab.html'),url('offline.html'),url('manifest.webmanifest'),url('chronologia.html'),url('kokugo-idioms.html'),url('kokugo-idioms-data.js'),url('chronologia-force1000-v1.js'),url('chronologia-v7-data-1.js'),url('chronologia-v7-data-2a.js'),url('chronologia-v7-data-2b.js'),url('chronologia-v7-data-3.js'),url('chronologia-v7-data-4.js'),url('chronologia-v7-overrides.js'),url('chronologia-curated-001-050.js'),url('chronologia-curated-051-100.js'),url('chronologia-curated-101-149.js'),url('chronologia-curated-150.js'),url('chronologia-curated-151-200.js'),url('chronologia-curated-201-250.js'),url('chronologia-curated-251-300.js'),url('chronologia-curated-301-350.js'),url('chronologia-curated-351-400.js'),url('chronologia-curated-401-450.js'),url('chronologia-curated-451-500.js'),url('chronologia-curated-501-600.js'),url('chronologia-curated-601-700.js'),url('chronologia-curated-701-800.js'),url('chronologia-curated-801-900.js'),url('chronologia-curated-901-1000.js'),url('chronologia-curated-final-fixes.js'),url('chronologia-daily-companion.js'),url('chronologia-live-companion.js'),url('learning-engine-v22.css'),url('review/'),url('review/index.html'),url('review.html'),url('review-bank-v1.js'),url('review-page-v1.js'),url('aa-companion-v2.js'),url('aa-companion-mobile-fix.js'),url('mobile-layout-guard-v1.js'),url('companion7-runtime.js'),url('login-companion-v1.js'),url('login-production-test-v1.js'),url('settings-improvements-v1.js'),url('v23-pet-settings.js'),url('v23-loader.js'),url('v23-english-gloss1.js'),url('v23-english-gloss2.js'),url('v23-english-gloss3.js'),url('v23-english-gloss-vocab.js'),url('v23-english-main.js'),url('english-vocab-examples-basic1-v1.js'),url('english-vocab-examples-basic2-v1.js'),url('english-vocab-examples-basic3-v1.js'),url('english-vocab-examples-phrases-v1.js'),url('english-vocab-examples-residual-v1.js'),url('english-vocab-examples-normalize-v1.js'),url('english-vocab-examples-apply-v1.js'),url('english-vocab-examples-context-v1.js'),url('english-vocab-example-ui-v1.js'),url('vocab-row-toggle-v1.js'),url('vocab-sort-v1.js'),url('quality-repair-v1.js'),url('quality-repair-final-v1.js'),url('quality-ci-runner-v1.js'),url('storage-resilience-v1.js'),url('reading-gloss-tap-v1.js'),url('reading-v23-ja-fix-v1.js'),url('answer-feedback-audio-v1.js'),url('companion-settings-only-guard-v1.js'),url('voice-selftest-v1.js'),url('analytics-daily-v1.js'),url('analytics-explosion-v1.js'),url('icons/apple-touch-icon-180.png'),url('icons/icon-192.png'),url('icons/icon-512.png')];
async function putIfGood(cache,request,response){if(response&&response.ok)await cache.put(request,response.clone());return response}
async function networkFirst(request,{reload=false}={}){const cache=await caches.open(CACHE_NAME);try{const response=await fetch(request,{cache:reload?'no-store':'no-cache'});return await putIfGood(cache,request,response)}catch(_){return(await cache.match(request))||(await caches.match(request))||null}}
async function cacheFirstRefresh(request,event){const cache=await caches.open(CACHE_NAME);const cached=await cache.match(request)||await caches.match(request);const refresh=fetch(request).then(r=>putIfGood(cache,request,r)).catch(()=>null);if(cached){event?.waitUntil(refresh);return cached}return(await refresh)||new Response('',{status:504,statusText:'Offline'})}
async function withChronologiaBootGuard(request,response){
 if(!response||!response.ok)return response;
 const u=new URL(request.url);
 if(!u.pathname.endsWith('/chronologia.html'))return response;
 const type=response.headers.get('content-type')||'';
 if(!type.includes('text/html'))return response;
 try{
  const html=await response.text();
  if(html.includes('id="chronologia-boot-guard"'))return new Response(html,{status:response.status,statusText:response.statusText,headers:response.headers});
  const guard=`<style id="chronologia-boot-guard">html.chronologia-booting .app{opacity:0!important;pointer-events:none!important}html.chronologia-booting body:before{content:"年表を準備中…";position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;padding:24px;background:#eef1f6;color:#152039;text-align:center;white-space:pre-line;font:700 16px -apple-system,BlinkMacSystemFont,"Hiragino Sans","Yu Gothic UI","Yu Gothic",sans-serif}html.chronologia-booting.chronologia-boot-error body:before{content:"最新の年表データを読み込めませんでした。\\A通信を確認して再読み込みしてください。"}</style><script id="chronologia-boot-guard-script">(()=>{const h=document.documentElement;h.classList.add('chronologia-booting');let done=false;const ready=()=>Number(h.dataset.chronologiaItems||0)>=1000||h.dataset.chronologiaReady==='1';const reveal=()=>{if(done)return;done=true;h.classList.remove('chronologia-booting','chronologia-boot-error')};document.addEventListener('chronologia:content-updated',e=>{if(Number(e.detail?.items)>=1000)requestAnimationFrame(reveal)});const timer=setInterval(()=>{if(ready()){clearInterval(timer);requestAnimationFrame(reveal)}},40);setTimeout(()=>{if(!ready())h.classList.add('chronologia-boot-error')},8000);addEventListener('pageshow',()=>{if(ready())reveal()})})();<\/script>`;
  const transformed=html.includes('</head>')?html.replace('</head>',guard+'</head>'):guard+html;
  const headers=new Headers(response.headers);headers.delete('content-length');headers.delete('content-encoding');headers.delete('etag');
  return new Response(transformed,{status:response.status,statusText:response.statusText,headers});
 }catch(_){return response}
}
self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await Promise.all(CORE.map(async href=>{try{const r=await fetch(href,{cache:'reload'});if(r.ok)await cache.put(href,r)}catch(_){}}));await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('asahigaoka-aa-os-')&&k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CLEAR_RUNTIME_CACHE')event.waitUntil(caches.delete(CACHE_NAME))});
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const u=new URL(request.url);if(u.origin!==self.location.origin||!u.href.startsWith(BASE))return;if(request.mode==='navigate'){event.respondWith((async()=>{const fresh=await networkFirst(request);if(fresh)return withChronologiaBootGuard(request,fresh);const fallback=(await caches.match(request))||(await caches.match(url('index.html')))||(await caches.match(url('offline.html')))||new Response('Offline',{status:503});return withChronologiaBootGuard(request,fallback)})());return}const ext=(u.pathname.split('.').pop()||'').toLowerCase();if(ext==='js'||ext==='css'||ext==='json'||ext==='webmanifest'){event.respondWith((async()=>{const fresh=await networkFirst(request,{reload:ext==='js'||u.pathname.endsWith('review-bank-v1.js')});return fresh||new Response('',{status:504,statusText:'Offline'})})());return}event.respondWith(cacheFirstRefresh(request,event))});