(()=>{'use strict';
if(window.__AA_VOCAB_SORT_V1__)return;window.__AA_VOCAB_SORT_V1__=true;
const KEY='aa-vocab-sort-v1',PER=40,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let mode='original',page=0,randomRank=new Map(),busy=false,queued=false,lastSignature='';
try{mode=localStorage.getItem(KEY)||'original'}catch(_){ }
const norm=s=>String(s??'').trim().toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function kind(v){if(v.pos==='phrase'||v.level==='phrase'||String(v.word).includes(' '))return'phrase';if(v.pos==='form'||v.level==='form')return'form';return'word'}
function lev(v){return v.level==='entrance'?'entrance':v.level==='phrase'||kind(v)==='phrase'?'phrase':v.level==='form'||kind(v)==='form'?'form':'core'}
function levLabel(v){return({core:'中学標準',entrance:'入試頻出',phrase:'熟語',form:'活用形'})[lev(v)]}
function pos(p){return({n:'名詞',v:'動詞',adj:'形容詞',adv:'副詞',prep:'前置詞',conj:'接続詞',pron:'代名詞',phrase:'熟語',form:'活用形','n/v':'名・動','v/adj':'動・形','adj/v':'形・動',mixed:'複合'})[p]||p||'—'}
function prog(v){const p=v.progress||{},s=+p.seen||0,c=+p.correct||0,l=+p.lapses||0,r=+p.retention||0;if(!s)return'new';if(p.due||(l>=2&&r<.85))return'weak';if(s>=2&&c/s>=.84&&r>=.72)return'mastered';return'learning'}
function progLabel(k){return({new:'未学習',learning:'学習中',weak:'要復習',mastered:'定着'})[k]}
function api(){try{return $('#engine')?.contentWindow?.AA_VOCAB_CATALOG_API||null}catch(_){return null}}
function allWords(){try{return(api()?.list?.()||[]).filter(v=>v?.id&&v?.word)}catch(_){return[]}}
function filtered(a){const q=norm($('#search')?.value),l=$('#level')?.value||'',k=$('#kind')?.value||'',p=$('#progress')?.value||'';return a.filter(v=>(!l||lev(v)===l)&&(!k||kind(v)===k)&&(!p||prog(v)===p)&&(!q||norm([v.word,v.meaning,v.example,(v.family||[]).join(' ')].join(' ')).includes(q)))}
function reviewScore(v){const p=v.progress||{},s=+p.seen||0,c=+p.correct||0,l=+p.lapses||0,r=+p.retention||0;let x=0;if(prog(v)==='weak')x+=10000;if(p.due)x+=5000;x+=l*700;x+=(1-r)*600;x+=(s?1-c/Math.max(1,s):1)*350;return x}
function levelScore(v){return({core:0,entrance:1,phrase:2,form:3})[lev(v)]??9}
function ensureRandom(a,force=false){const sig=a.map(v=>String(v.id)).join('|');if(force||!randomRank.size||sig!==lastSignature){lastSignature=sig;const ids=a.map(v=>String(v.id));for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}randomRank=new Map(ids.map((id,i)=>[id,i]))}}
function sorted(a){const out=a.slice();if(mode==='original')return out;if(mode==='abc')return out.sort((a,b)=>String(a.word).localeCompare(String(b.word),'en',{sensitivity:'base'}));if(mode==='abc-desc')return out.sort((a,b)=>String(b.word).localeCompare(String(a.word),'en',{sensitivity:'base'}));if(mode==='meaning')return out.sort((a,b)=>String(a.meaning||'').localeCompare(String(b.meaning||''),'ja'));if(mode==='level')return out.sort((a,b)=>levelScore(a)-levelScore(b)||String(a.word).localeCompare(String(b.word),'en'));if(mode==='level-desc')return out.sort((a,b)=>levelScore(b)-levelScore(a)||String(a.word).localeCompare(String(b.word),'en'));if(mode==='review')return out.sort((a,b)=>reviewScore(b)-reviewScore(a)||String(a.word).localeCompare(String(b.word),'en'));if(mode==='new')return out.sort((a,b)=>(prog(a)==='new'?0:1)-(prog(b)==='new'?0:1)||String(a.word).localeCompare(String(b.word),'en'));if(mode==='recent')return out.sort((a,b)=>(+b.progress?.lastReviewAt||0)-(+a.progress?.lastReviewAt||0)||String(a.word).localeCompare(String(b.word),'en'));if(mode==='random'){ensureRandom(allWords());return out.sort((a,b)=>(randomRank.get(String(a.id))??1e9)-(randomRank.get(String(b.id))??1e9))}return out}
function tr(v,i){const p=prog(v);return `<tr><td>${i+1}</td><td><span class="word">${esc(v.word)}</span></td><td class="pos">${esc(pos(v.pos))}</td><td>${esc(v.meaning||'—')}</td><td><span class="tag">${levLabel(v)}</span></td><td><span class="state ${p}">${progLabel(p)}</span></td><td><button class="speak" data-s="${esc(v.id)}">🔊</button></td></tr>`}
function say(t){try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}catch(_){}}
function render(){if(mode==='original'||busy)return;const words=allWords();if(!words.length)return;busy=true;try{const a=sorted(filtered(words)),max=Math.max(1,Math.ceil(a.length/PER));page=Math.max(0,Math.min(page,max-1));const st=page*PER;if($('#count'))$('#count').textContent=`${a.length.toLocaleString()}語句`;if($('#rows'))$('#rows').innerHTML=a.slice(st,st+PER).map((v,i)=>tr(v,st+i)).join('')||'<tr><td colspan="7">該当なし</td></tr>';if($('#page'))$('#page').textContent=`${page+1} / ${max}`;if($('#prev'))$('#prev').disabled=page===0;if($('#next'))$('#next').disabled=page>=max-1;$$('#rows [data-s]').forEach(b=>b.onclick=e=>{e.stopPropagation();const v=words.find(x=>String(x.id)===b.dataset.s);if(v)say(v.word)});document.dispatchEvent(new CustomEvent('aa:vocabSorted',{detail:{mode,count:a.length,page:page+1,pages:max}}))}finally{busy=false}}
function schedule(){if(mode==='original'||queued)return;queued=true;setTimeout(()=>{queued=false;render()},0)}
function install(attempt=0){const filters=$('#listView .filters'),rows=$('#rows'),prev=$('#prev'),next=$('#next');if(!filters||!rows||!prev||!next){if(attempt<100)setTimeout(()=>install(attempt+1),100);return}if($('#aa-vocab-sort'))return;
 const wrap=document.createElement('div');wrap.id='aa-vocab-sort-wrap';wrap.innerHTML='<label for="aa-vocab-sort">並び順</label><select id="aa-vocab-sort"><option value="original">元の順</option><option value="abc">ABC順 A→Z</option><option value="abc-desc">ABC順 Z→A</option><option value="meaning">日本語順</option><option value="level">レベル 基礎→発展</option><option value="level-desc">レベル 発展→基礎</option><option value="review">要復習を優先</option><option value="new">未学習を優先</option><option value="recent">最近学習した順</option><option value="random">ランダム</option></select>';
 const style=document.createElement('style');style.id='aa-vocab-sort-style';style.textContent='#aa-vocab-sort-wrap{display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:8px;margin:9px 0 2px;padding:9px 10px;border:1px solid var(--line);border-radius:11px;background:#f8fafc}#aa-vocab-sort-wrap label{font-size:12px;font-weight:900;color:var(--sub);white-space:nowrap}#aa-vocab-sort{width:100%;min-height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);padding:8px;font-weight:800}@media(max-width:480px){#aa-vocab-sort-wrap{grid-template-columns:1fr;padding:8px}#aa-vocab-sort-wrap label{font-size:11px}}';document.head.appendChild(style);
 const recall=$('#aa-vocab-recall-controls');(recall||filters).insertAdjacentElement('afterend',wrap);const select=$('#aa-vocab-sort');if(!select.querySelector(`option[value="${CSS.escape(mode)}"]`))mode='original';select.value=mode;
 select.addEventListener('change',()=>{mode=select.value;page=0;try{localStorage.setItem(KEY,mode)}catch(_){}if(mode==='random')ensureRandom(allWords(),true);if(mode==='original'){const s=$('#search');if(s)s.dispatchEvent(new Event('input',{bubbles:true}));return}render()});
 ['search','level','kind','progress'].forEach(id=>$('#'+id)?.addEventListener(id==='search'?'input':'change',()=>{page=0;schedule()}));prev.addEventListener('click',()=>{if(mode==='original')return;page=Math.max(0,page-1);schedule()});next.addEventListener('click',()=>{if(mode==='original')return;page++;schedule()});
 const mo=new MutationObserver(()=>{if(busy||mode==='original')return;schedule()});mo.observe(rows,{childList:true});
 if(mode==='random')ensureRandom(allWords(),true);schedule();document.body?.setAttribute('data-aa-vocab-sort','v1')}
install();
})();
