(()=>{
'use strict';
const VERSION='1.0.0';
const PROGRESS_KEY='rise_reading_v2_progress_v1';
const MANIFEST_URL='../reading-v2-data/manifest.json';
const batchCache=new Map();
let manifest=null,current=null,graded=false;
const $=id=>document.getElementById(id);
const els={levels:$('levels'),status:$('status'),total:$('totalCount'),done:$('doneCount'),remain:$('remainCount'),newButton:$('newButton'),readingCard:$('readingCard'),emptyCard:$('emptyCard'),readingLevel:$('readingLevel'),readingId:$('readingId'),readingTitle:$('readingTitle'),passage:$('passage'),questions:$('questions'),submit:$('submitButton'),result:$('result'),score:$('score'),translation:$('translation'),explanations:$('explanations'),next:$('nextButton')};
function readProgress(){try{const x=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');return x&&typeof x==='object'&&x.answers&&typeof x.answers==='object'?x:{version:1,answers:{}}}catch(_){return{version:1,answers:{}}}}
function saveProgress(p){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));return true}catch(_){setStatus('進捗を保存できませんでした。ブラウザの保存設定を確認してください。',true);return false}}
function selectedLevels(){return[...els.levels.querySelectorAll('input:checked')].map(x=>Number(x.value))}
function allIndex(){return Array.isArray(manifest?.index)?manifest.index:[]}
function eligibleIndex(){const p=readProgress(),levels=new Set(selectedLevels());return allIndex().filter(x=>levels.has(Number(x.level))&&!p.answers[x.id])}
function updateStats(){if(!manifest)return;const p=readProgress(),idx=allIndex(),done=idx.filter(x=>p.answers[x.id]).length;els.total.textContent=String(idx.length);els.done.textContent=String(done);els.remain.textContent=String(Math.max(0,idx.length-done));const left=eligibleIndex().length;setStatus(left?`選択中のLevelに未回答が ${left} 作あります。`:'選択中のLevelに未回答はありません。')}
function setStatus(text,error=false){els.status.textContent=text;els.status.classList.toggle('error',Boolean(error))}
function randomOne(list){if(!list.length)return null;try{const a=new Uint32Array(1);crypto.getRandomValues(a);return list[a[0]%list.length]}catch(_){return list[Math.floor(Math.random()*list.length)]}}
async function loadBatch(file){if(batchCache.has(file))return batchCache.get(file);const url=`../reading-v2-data/${encodeURIComponent(file)}`;const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`問題データ ${file} を取得できませんでした (${r.status})`);const data=await r.json();if(!Array.isArray(data))throw new Error(`${file} の形式が不正です`);batchCache.set(file,data);return data}
async function pickNew(){if(!manifest)return;const levels=selectedLevels();if(!levels.length){setStatus('Levelを1つ以上選んでください。',true);return}const candidates=eligibleIndex();if(!candidates.length){current=null;graded=false;els.readingCard.classList.remove('active');els.emptyCard.classList.add('active');updateStats();return}els.emptyCard.classList.remove('active');els.newButton.disabled=true;setStatus('新しい長文を選んでいます…');try{const chosen=randomOne(candidates),batch=await loadBatch(chosen.file),item=batch.find(x=>x.id===chosen.id);if(!item)throw new Error(`問題 ${chosen.id} が見つかりません`);validateItem(item);current=item;graded=false;renderReading();setStatus(`未回答から Level ${item.level} を選びました。`)}catch(e){setStatus(e.message||'問題の読み込みに失敗しました。',true)}finally{els.newButton.disabled=false}}
function validateItem(x){if(!x||typeof x.id!=='string'||!Number.isInteger(x.level)||x.level<1||x.level>5||!x.title||!x.passage||!x.translation)throw new Error('問題データの必須項目が不足しています');if(!Array.isArray(x.questions)||x.questions.length!==5)throw new Error(`${x.id}: 設問は5問必要です`);x.questions.forEach((q,i)=>{if(!q.question||!Array.isArray(q.choices)||q.choices.length!==4||!Number.isInteger(q.answer)||q.answer<0||q.answer>3||!q.explanation)throw new Error(`${x.id}: Q${i+1} の形式が不正です`)})}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderReading(){const x=current;if(!x)return;els.readingLevel.textContent=`Level ${x.level}`;els.readingId.textContent=x.id;els.readingTitle.textContent=x.title;els.passage.textContent=x.passage;els.questions.innerHTML=x.questions.map((q,qi)=>`<section class="question" data-q="${qi}"><h3>Q${qi+1}. ${escapeHtml(q.question)}</h3>${q.choices.map((c,ci)=>`<label class="choice"><input type="radio" name="q${qi}" value="${ci}"><span>${escapeHtml(c)}</span></label>`).join('')}</section>`).join('');els.result.classList.remove('active');els.submit.disabled=false;els.submit.style.display='inline-block';els.readingCard.classList.add('active');els.readingCard.scrollIntoView({behavior:'smooth',block:'start'})}
function grade(){if(!current||graded)return;const answers=current.questions.map((_,i)=>els.questions.querySelector(`input[name="q${i}"]:checked`));if(answers.some(x=>!x)){setStatus('5問すべて答えてから採点してください。',true);return}let score=0;answers.forEach((input,i)=>{const selected=Number(input.value),correct=current.questions[i].answer;if(selected===correct)score++;const section=els.questions.querySelector(`[data-q="${i}"]`);[...section.querySelectorAll('.choice')].forEach((label,ci)=>{if(ci===correct)label.classList.add('correct');else if(ci===selected)label.classList.add('wrong')});[...section.querySelectorAll('input')].forEach(x=>x.disabled=true)});graded=true;els.score.textContent=`${score} / 5`;els.translation.textContent=current.translation;els.explanations.innerHTML=current.questions.map((q,i)=>`<div class="explanation"><b>Q${i+1}</b>　${escapeHtml(q.explanation)}</div>`).join('');els.result.classList.add('active');els.submit.disabled=true;els.submit.style.display='none';const p=readProgress();p.answers[current.id]={score,total:5,completedAt:new Date().toISOString(),level:current.level};saveProgress(p);updateStats();els.result.scrollIntoView({behavior:'smooth',block:'start'})}
function renderLevels(){els.levels.innerHTML=[1,2,3,4,5].map(n=>`<label class="level"><input type="checkbox" value="${n}" ${n>=3?'checked':''}><span>Lv ${n}</span></label>`).join('');els.levels.addEventListener('change',updateStats)}
async function boot(){renderLevels();els.newButton.disabled=true;try{const r=await fetch(MANIFEST_URL,{cache:'no-store'});if(!r.ok)throw new Error(`manifestを取得できませんでした (${r.status})`);manifest=await r.json();if(!manifest||!Array.isArray(manifest.index)||!Array.isArray(manifest.batches))throw new Error('manifestの形式が不正です');const seen=new Set();for(const x of manifest.index){if(!x.id||!Number.isInteger(Number(x.level))||!x.file||seen.has(x.id))throw new Error('manifestのID・Level・fileに不整合があります');seen.add(x.id)}updateStats();els.newButton.disabled=false}catch(e){setStatus(e.message||'問題データを読み込めませんでした。',true)}}
els.newButton.addEventListener('click',()=>void pickNew());els.submit.addEventListener('click',grade);els.next.addEventListener('click',()=>void pickNew());boot();window.__RISE_READING_V2__=Object.freeze({version:VERSION,progressKey:PROGRESS_KEY});
})();
