(()=>{
'use strict';
const VERSION='1.1.0';
const PROGRESS_KEY='rise_reading_v2_progress_v1';
const MANIFEST_URL='../reading-v2-data/manifest.json';
const batchCache=new Map();
let manifest=null,current=null,translationShown=false;
const $=id=>document.getElementById(id);
const els={levels:$('levels'),status:$('status'),total:$('totalCount'),done:$('doneCount'),remain:$('remainCount'),newButton:$('newButton'),readingCard:$('readingCard'),emptyCard:$('emptyCard'),readingLevel:$('readingLevel'),readingId:$('readingId'),readingTitle:$('readingTitle'),passage:$('passage'),translation:$('translation'),translationPanel:$('translationPanel')||$('result'),showTranslation:$('showTranslationButton')||$('submitButton'),next:$('nextButton'),questions:$('questions'),explanations:$('explanations'),score:$('score')};
function readProgress(){try{const x=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');return x&&typeof x==='object'&&x.answers&&typeof x.answers==='object'?x:{version:1,answers:{}}}catch(_){return{version:1,answers:{}}}}
function saveProgress(p){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));return true}catch(_){setStatus('進捗を保存できませんでした。ブラウザの保存設定を確認してください。',true);return false}}
function selectedLevels(){return[...els.levels.querySelectorAll('input:checked')].map(x=>Number(x.value))}
function allIndex(){return Array.isArray(manifest?.index)?manifest.index:[]}
function unreadIndex(){const p=readProgress(),levels=new Set(selectedLevels());return allIndex().filter(x=>levels.has(Number(x.level))&&!p.answers[x.id])}
function setStatus(text,error=false){els.status.textContent=text;els.status.classList.toggle('error',Boolean(error))}
function updateStats(){if(!manifest)return;const p=readProgress(),idx=allIndex(),done=idx.filter(x=>p.answers[x.id]).length;els.total.textContent=String(idx.length);els.done.textContent=String(done);els.remain.textContent=String(Math.max(0,idx.length-done));const left=unreadIndex().length;setStatus(left?`選択中のLevelに未読長文が ${left} 作あります。`:'選択中のLevelに未読長文はありません。')}
function randomOne(list){if(!list.length)return null;try{const a=new Uint32Array(1);crypto.getRandomValues(a);return list[a[0]%list.length]}catch(_){return list[Math.floor(Math.random()*list.length)]}}
async function loadBatch(file){if(batchCache.has(file))return batchCache.get(file);const r=await fetch(`../reading-v2-data/${encodeURIComponent(file)}`,{cache:'no-store'});if(!r.ok)throw new Error(`長文データ ${file} を取得できませんでした (${r.status})`);const data=await r.json();if(!Array.isArray(data))throw new Error(`${file} の形式が不正です`);batchCache.set(file,data);return data}
function validateItem(x){if(!x||typeof x.id!=='string'||!Number.isInteger(x.level)||x.level<1||x.level>5||!x.title||!x.passage||!x.translation)throw new Error('長文データの必須項目が不足しています')}
function markRead(){if(!current)return;const p=readProgress();if(!p.answers[current.id]){p.answers[current.id]={readAt:new Date().toISOString(),level:current.level};saveProgress(p)}updateStats()}
function renderReading(){const x=current;if(!x)return;translationShown=false;els.readingLevel.textContent=`Level ${x.level}`;els.readingId.textContent=x.id;els.readingTitle.textContent=x.title;els.passage.textContent=x.passage;els.translation.textContent=x.translation;if(els.questions){els.questions.innerHTML='';els.questions.style.display='none'}if(els.explanations)els.explanations.innerHTML='';if(els.score)els.score.textContent='';if(els.translationPanel)els.translationPanel.classList.remove('active');if(els.translationPanel)els.translationPanel.hidden=true;if(els.showTranslation){els.showTranslation.style.display='inline-block';els.showTranslation.disabled=false;els.showTranslation.textContent='日本語訳を見る'}els.readingCard.classList.add('active');els.readingCard.scrollIntoView({behavior:'smooth',block:'start'})}
function showTranslation(){if(!current||translationShown)return;translationShown=true;markRead();if(els.translationPanel){els.translationPanel.hidden=false;els.translationPanel.classList.add('active')}if(els.showTranslation)els.showTranslation.style.display='none';setStatus('読了として記録しました。次は未読の長文から選びます。');els.translationPanel?.scrollIntoView({behavior:'smooth',block:'start'})}
async function pickNew(){if(!manifest)return;const levels=selectedLevels();if(!levels.length){setStatus('Levelを1つ以上選んでください。',true);return}const candidates=unreadIndex();if(!candidates.length){current=null;translationShown=false;els.readingCard.classList.remove('active');els.emptyCard.classList.add('active');updateStats();return}els.emptyCard.classList.remove('active');els.newButton.disabled=true;setStatus('新しい長文を選んでいます…');try{const chosen=randomOne(candidates),batch=await loadBatch(chosen.file),item=batch.find(x=>x.id===chosen.id);if(!item)throw new Error(`長文 ${chosen.id} が見つかりません`);validateItem(item);current=item;renderReading();setStatus(`未読から Level ${item.level} を選びました。`)}catch(e){setStatus(e.message||'長文の読み込みに失敗しました。',true)}finally{els.newButton.disabled=false}}
function renderLevels(){els.levels.innerHTML=[1,2,3,4,5].map(n=>`<label class="level"><input type="checkbox" value="${n}" ${n>=3?'checked':''}><span>Lv ${n}</span></label>`).join('');els.levels.addEventListener('change',updateStats)}
async function boot(){renderLevels();els.newButton.disabled=true;try{const r=await fetch(MANIFEST_URL,{cache:'no-store'});if(!r.ok)throw new Error(`manifestを取得できませんでした (${r.status})`);manifest=await r.json();if(!manifest||!Array.isArray(manifest.index)||!Array.isArray(manifest.batches))throw new Error('manifestの形式が不正です');const seen=new Set();for(const x of manifest.index){if(!x.id||!Number.isInteger(Number(x.level))||!x.file||seen.has(x.id))throw new Error('manifestのID・Level・fileに不整合があります');seen.add(x.id)}updateStats();els.newButton.disabled=false}catch(e){setStatus(e.message||'長文データを読み込めませんでした。',true)}}
els.newButton.addEventListener('click',()=>void pickNew());els.showTranslation?.addEventListener('click',showTranslation);els.next?.addEventListener('click',()=>void pickNew());boot();window.__RISE_READING_V2__=Object.freeze({version:VERSION,progressKey:PROGRESS_KEY});
})();
