import {PROFILE,seededRandom,shuffle,hashSeed,validateQuestion,assertExam} from './core.mjs';
const pick=(r,a)=>a[Math.floor(r()*a.length)],fmt=n=>Number.isInteger(n)?String(n):String(Math.round(n*100)/100);
function single({seed,key,domain,title,stimulus,stem,answer,wrong,explanation,steps,skills,points=1,level='application',seconds=90}){
 const random=seededRandom(seed+key),rows=shuffle([{text:String(answer),ok:true,explanation},...wrong.map(x=>({text:String(x[0]),ok:false,distractorType:x[1],explanation:x[2]}))],random).map((x,i)=>({...x,id:'c'+(i+1)}));
 const a=rows.find(x=>x.ok);const q={id:key+'-'+hashSeed(seed+key).toString(36),templateKey:key,title,domain,format:'single_choice',points,level,expectedSeconds:seconds,stem,
  stimuli:[{label:stimulus[0],kind:stimulus[1],content:stimulus[2]}],choices:rows.map(({ok,...x})=>x),answers:[a.id],intent:'資料・条件を整理し、根拠を使って判断する。',explanation,reasoningSteps:steps,skills,
  audit:{method:'deterministic-recompute',verified:true,recomputedAnswer:String(answer)}};
 const v=validateQuestion(q);if(!v.ok)throw new Error(key+': '+v.errors.join(','));return q;
}
const T=[
 ['bio_photosynthesis','biology',s=>single({seed:s,key:'bio_photosynthesis',domain:'biology',title:'光合成と対照実験',level:'standard',seconds:55,stimulus:['実験','experiment','葉の一部をアルミニウムはくで覆い、数時間光を当てた後に脱色してヨウ素液をつけると、光が当たった部分だけ青紫色になった。'],stem:'この実験から直接確かめられることとして最も適切なものを選びなさい。',answer:'光が当たった部分ではデンプンがつくられた。',wrong:[['葉のすべての部分で同量のデンプンがつくられた。','scope_overreach','覆った部分との違いを無視しています。'],['光がなくても同じ速さで光合成する。','cause_effect_reverse','結果は光の有無による差を示しています。'],['ヨウ素液がデンプンをつくった。','concept_confusion','ヨウ素液はデンプンを検出する試薬です。']],explanation:'青紫色はデンプンがあることを示し、光が当たった部分だけで反応したためです。',steps:['比較条件は光の有無。','青紫色はデンプンの存在を示す。','条件と結果の差を結びつける。'],skills:['sci.biology.photosynthesis','sci.experiment.control']}))],
 ['bio_enzyme','biology',s=>{const r=seededRandom(s),lo=pick(r,[2,3]),mid=pick(r,[10,12,14]),hi=pick(r,[5,6,7]);return single({seed:s,key:'bio_enzyme',domain:'biology',title:'消化酵素と温度',stimulus:['結果','table',`同量のデンプン液とだ液を10℃・37℃・70℃で反応させた。できた糖の相対量は順に${lo}、${mid}、${hi}。その他の条件は同じ。`],stem:'結果から最も適切にいえることを選びなさい。',answer:'この条件では37℃のときにデンプンの分解が最も進んだ。',wrong:[['温度が高いほど必ず分解が速い。','scope_overreach','70℃は37℃より糖が少ないため成り立ちません。'],['70℃で最も分解が進んだ。','data_misread','最大値は37℃です。'],['温度以外の条件の違いが原因である。','control_variable_error','その他の条件は同じです。']],explanation:'生成した糖の量が最大の37℃で分解が最も進んだと判断します。',steps:['生成物の量を比較。','最大値の条件を特定。','実験範囲を超えて一般化しない。'],skills:['sci.biology.digestion','sci.experiment.data']}))}],
 ['bio_genetics','biology',s=>single({seed:s,key:'bio_genetics',domain:'biology',title:'遺伝と検定交雑',seconds:105,stimulus:['交配','data','丸形をA、しわ形をaとする。丸形Xとaaを交配すると、子は丸形29個・しわ形31個でほぼ1:1だった。'],stem:'個体Xの遺伝子型として最も適切なものを選びなさい。',answer:'Aa',wrong:[['AA','concept_confusion','AA×aaなら子はすべて丸形です。'],['aa','concept_confusion','aaならX自身がしわ形です。'],['AAまたはaa','scope_overreach','1:1はAa×aaで説明できます。']],explanation:'Aa×aaではAaとaaが1:1で生じます。',steps:['相手はaa。','AAなら丸形のみ、Aaなら1:1。','観察比と照合。'],skills:['sci.biology.genetics','sci.biology.ratio']}))],
 ['bio_transpiration','biology',s=>single({seed:s,key:'bio_transpiration',domain:'biology',title:'蒸散と気孔',stimulus:['質量減少','table','同じ枝を2時間置いた。無処理5.0g、葉の裏面だけワセリン2.9g、葉の両面ワセリン0.6gの質量減少だった。'],stem:'最もよく支持される考えを選びなさい。',answer:'この葉では蒸散は主に葉の裏面から起こっている。',wrong:[['蒸散は表面から全く起こらない。','scope_overreach','「全く」とまではいえません。'],['ワセリンを塗るほど蒸散量が増える。','inverse_relation','実際には減っています。'],['裏面をふさいでも結果は変わらない。','data_misread','5.0gから2.9gへ減っています。']],explanation:'裏面をふさぐと質量減少が大きく小さくなるため、裏面の寄与が大きいと考えます。',steps:['質量減少を蒸散量の指標にする。','裏面をふさいだ差を見る。','「主に」と「全く」を区別。'],skills:['sci.biology.transpiration','sci.experiment.control']}))],
 ['bio_ecosystem','biology',s=>single({seed:s,key:'bio_ecosystem',domain:'biology',title:'食物連鎖と個体数',stimulus:['食物関係','diagram_text','植物プランクトン → 動物プランクトン → 小魚。小魚だけが急減し、他の環境条件は大きく変わらなかった。'],stem:'直後に起こりやすい変化として最も適切なものを選びなさい。',answer:'動物プランクトンが増え、植物プランクトンが減る。',wrong:[['動物プランクトンが減り、植物プランクトンが増える。','cause_effect_reverse','捕食圧の変化が逆です。'],['両者とも必ず変化しない。','condition_omission','食物関係の影響を無視しています。'],['植物プランクトンだけが直ちに全滅する。','scope_overreach','全滅までの根拠はありません。']],explanation:'小魚減少で動物プランクトンが捕食されにくくなり、その増加で植物プランクトンが減りやすくなります。',steps:['直接影響を考える。','次に二段階目の影響を追う。'],skills:['sci.biology.ecosystem','sci.biology.causal_chain']}))],
 ['chem_mass','chemistry',s=>{const r=seededRandom(s),m=pick(r,[22,28,34]);return single({seed:s,key:'chem_mass',domain:'chemistry',title:'質量保存',level:'standard',seconds:45,stimulus:['実験','condition',`密閉容器全体の反応前質量は${m}.0g。内部で気体が発生したが、ふたは開けなかった。`],stem:'反応後の容器全体の質量を選びなさい。',answer:`${m}.0 g`,wrong:[[`$${m-2}.0 g`.replace('$',''),'condition_omission','気体も容器内に残っています。'],[`${m+2}.0 g`,'concept_confusion','化学反応で全質量が増えるわけではありません。'],['気体が発生したので判断できない','condition_omission','密閉条件から判断できます。']],explanation:'密閉系では物質の出入りがないため全質量は保存されます。',steps:['密閉か確認。','気体も系に含める。','質量保存を適用。'],skills:['sci.chemistry.mass_conservation']}))}],
 ['chem_ratio','chemistry',s=>{const r=seededRandom(s),cu=pick(r,[4,6,8,10]),o=cu/4,total=cu+o;return single({seed:s,key:'chem_ratio',domain:'chemistry',title:'酸化と質量比',seconds:110,stimulus:['関係','data','銅を完全に酸化させると、銅:結びついた酸素の質量比が4:1になった。'],stem:`${cu}gの銅を完全に酸化したときの酸化物の質量を選びなさい。`,answer:`${fmt(total)} g`,wrong:[[`$${fmt(o)} g`.replace('$',''),'intermediate_value','酸素だけの質量です。'],[`${fmt(cu-o)} g`,'formula_substitution','酸化では酸素が加わります。'],[`${cu*4} g`,'proportion_error','4:1を4倍と誤解しています。']],explanation:`酸素は${fmt(o)}gなので合計${fmt(total)}gです。`,steps:['4:1から酸素量を求める。','銅と酸素を足す。'],skills:['sci.chemistry.oxidation','sci.chemistry.proportion']}))}],
 ['chem_solubility','chemistry',s=>{const hot=80,cold=30,d=70,a=40;return single({seed:s,key:'chem_solubility',domain:'chemistry',title:'溶解度と再結晶',seconds:120,stimulus:['溶解度','table',`水100gに溶けるXは60℃で${hot}g、20℃で${cold}g。60℃でXを${d}g溶かした。`],stem:'20℃まで冷やしたとき析出する結晶の質量を選びなさい。',answer:`${a} g`,wrong:[[`$${cold} g`.replace('$',''),'intermediate_value','冷却後に溶けていられる量です。'],[`${d} g`,'condition_omission','冷却後も最初に溶けていた全量がそのまま結晶になると誤っています。'],[`${d+cold} g`,'formula_substitution','析出量は差です。']],explanation:`${d}-${cold}=${a}gが析出します。`,steps:['実際に溶けた量を確認。','20℃で残れる量を読む。','差をとる。'],skills:['sci.chemistry.solubility','sci.chemistry.data']}))}],
 ['chem_neutral','chemistry',s=>single({seed:s,key:'chem_neutral',domain:'chemistry',title:'中和と比例',seconds:105,stimulus:['結果','data','同じ濃度条件で、塩酸10mLを中和するのに水酸化ナトリウム水溶液12mLが必要だった。'],stem:'同じ水溶液で塩酸25mLを中和するのに必要な水酸化ナトリウム水溶液を選びなさい。',answer:'30 mL',wrong:[['20.8 mL','inverse_relation','比例関係を逆にしています。'],['25 mL','condition_omission','10:12の比を無視しています。'],['37 mL','formula_substitution','単純な加算ではありません。']],explanation:'10:12=25:30なので30mLです。',steps:['体積比10:12を求める。','塩酸25mLへ比例させる。'],skills:['sci.chemistry.neutralization','sci.chemistry.proportion']}))],
 ['chem_gas','chemistry',s=>single({seed:s,key:'chem_gas',domain:'chemistry',title:'気体の同定',level:'standard',seconds:60,stimulus:['観察','table','無色の気体を石灰水に通すと白くにごった。火のついた線香を入れても燃え方は強くならなかった。'],stem:'この気体を選びなさい。',answer:'二酸化炭素',wrong:[['酸素','concept_confusion','酸素なら線香の燃え方が強くなります。'],['水素','concept_confusion','石灰水の白濁とは対応しません。'],['アンモニア','concept_confusion','刺激臭などの特徴とも合いません。']],explanation:'石灰水を白くにごらせる代表的な気体は二酸化炭素です。',steps:['観察結果を整理。','確認法と照合。'],skills:['sci.chemistry.gas']}))],
 ['phy_circuit','physics',s=>{const r=seededRandom(s),z=pick(r,[[12,20,40],[9,10,20],[6,10,20]]),v=z[0],r1=z[1],r2=z[2],rt=r1+r2,a=v/rt;return single({seed:s,key:'phy_circuit',domain:'physics',title:'直列回路',points:2,seconds:135,stimulus:['回路','diagram_text',`${v}V電源に${r1}Ωと${r2}Ωを直列接続した。`],stem:'回路を流れる電流を選びなさい。',answer:`${fmt(a)} A`,wrong:[[`${fmt(v/r1)} A`,'condition_omission','一方の抵抗しか使っていません。'],[`${fmt(v/r2)} A`,'condition_omission','一方の抵抗しか使っていません。'],[`${fmt(v/(r1*r2/(r1+r2)))} A`,'concept_confusion','並列の合成抵抗を使っています。']],explanation:`合成抵抗${rt}Ω、I=${v}/${rt}=${fmt(a)}Aです。`,steps:['直列なので抵抗を加算。','I=V/Rを適用。'],skills:['sci.physics.circuit','sci.physics.multistep']}))}],
 ['phy_ohm','physics',s=>{const r=seededRandom(s),R=pick(r,[20,30,40]),v=pick(r,[6,12]),i=v/R;return single({seed:s,key:'phy_ohm',domain:'physics',title:'オームの法則',stimulus:['測定','data',`抵抗Xに${v}Vを加えると${fmt(i)}A流れた。`],stem:'抵抗Xの抵抗値を選びなさい。',answer:`${R} Ω`,wrong:[[`${fmt(i/v)} Ω`,'formula_substitution','I/Vではありません。'],[`${fmt(v*i)} Ω`,'formula_substitution','V×Iではありません。'],[`${R*2} Ω`,'proportion_error','R=V/Iで直接求められます。']],explanation:`R=V/I=${v}/${fmt(i)}=${R}Ωです。`,steps:['V=IRを使う。','R=V/Iへ変形。'],skills:['sci.physics.ohm','sci.physics.ratio']}))}],
 ['phy_motion','physics',s=>single({seed:s,key:'phy_motion',domain:'physics',title:'平均の速さ',stimulus:['記録','table','台車が0.25秒の間に1.0m進んだ。'],stem:'この区間の平均の速さを選びなさい。',answer:'4 m/s',wrong:[['0.25 m/s','inverse_relation','時間÷距離になっています。'],['1.25 m/s','formula_substitution','距離と時間を足してはいけません。'],['240 m/s','unit_conversion','不要な分換算をしています。']],explanation:'1.0÷0.25=4m/sです。',steps:['速さ=距離÷時間。','mとsのまま計算。'],skills:['sci.physics.motion','sci.physics.rate']}))],
 ['phy_pressure','physics',s=>single({seed:s,key:'phy_pressure',domain:'physics',title:'圧力',level:'standard',seconds:65,stimulus:['条件','data','床を押す力120N、接触面積0.02m²。'],stem:'床が受ける圧力を選びなさい。',answer:'6000 Pa',wrong:[['2.4 Pa','formula_substitution','力×面積ではありません。'],['0.00017 Pa','inverse_relation','面積÷力ではありません。'],['120 Pa','condition_omission','面積を無視しています。']],explanation:'120÷0.02=6000Paです。',steps:['P=F/A。','Nとm²を確認。'],skills:['sci.physics.pressure']}))],
 ['phy_energy','physics',s=>single({seed:s,key:'phy_energy',domain:'physics',title:'エネルギー効率',stimulus:['装置','data','入力500Jのうち目的に利用できたエネルギーは350Jだった。'],stem:'変換効率を選びなさい。',answer:'70 %',wrong:[['30 %','cause_effect_reverse','失われた割合です。'],['1.43 %','inverse_relation','入力÷出力になっています。'],['350 %','unit_conversion','Jの値をそのまま%にしています。']],explanation:'350÷500×100=70%です。',steps:['有効出力÷入力。','100を掛ける。'],skills:['sci.physics.energy','sci.physics.ratio']}))],
 ['earth_humidity','earth',s=>single({seed:s,key:'earth_humidity',domain:'earth',title:'湿度',points:2,seconds:140,stimulus:['空気','data','飽和水蒸気量17.3g/m³、実際の水蒸気量10.38g/m³。'],stem:'湿度を選びなさい。',answer:'60 %',wrong:[['40 %','cause_effect_reverse','不足割合と取り違えています。'],['166.67 %','inverse_relation','分子と分母が逆です。'],['10.38 %','unit_conversion','水蒸気量をそのまま%にしています。']],explanation:'10.38÷17.3×100=60%です。',steps:['実際量÷飽和量。','100を掛ける。'],skills:['sci.earth.humidity','sci.earth.multistep']}))],
 ['earth_front','earth',s=>single({seed:s,key:'earth_front',domain:'earth',title:'前線通過',stimulus:['観測','time_series','強い雨の後、風が南寄りから西寄りへ変わり、気温18℃から12℃へ急低下。気圧は低下から上昇へ転じた。'],stem:'通過した前線として最も考えやすいものを選びなさい。',answer:'寒冷前線',wrong:[['温暖前線','concept_confusion','急な気温低下と合いません。'],['停滞前線','condition_omission','短時間の明瞭な通過変化です。'],['前線は通過していない','data_misread','複数要素が一連に変化しています。']],explanation:'強い雨、風向変化、急な気温低下、通過後の気圧上昇は寒冷前線と整合します。',steps:['気温・風向・気圧・雨を統合。','通過前後を比較。'],skills:['sci.earth.weather','sci.earth.integration']}))],
 ['earth_seismic','earth',s=>{const r=seededRandom(s),d=pick(r,[4,5,6,8]),ans=d*6;return single({seed:s,key:'earth_seismic',domain:'earth',title:'P波とS波',seconds:120,stimulus:['モデル','data',`P波6km/s、S波3km/s。P波到着からS波到着まで${d}秒。`],stem:'震源から観測点までの距離を選びなさい。',answer:`${ans} km`,wrong:[[`${d*3} km`,'intermediate_value','S波速度に時間差を直接掛けています。'],[`${d*18} km`,'formula_substitution','二つの速度を掛ける式ではありません。'],[`${ans+6} km`,'proportion_error','到着差は距離/6なので距離は時間差の6倍です。']],explanation:`到着差=d/3-d/6=d/6。距離=${d}×6=${ans}kmです。`,steps:['各到着時間を距離/速度で表す。','差を観測値に等しくする。'],skills:['sci.earth.seismic','sci.earth.model']}))}],
 ['earth_strata','earth',s=>single({seed:s,key:'earth_strata',domain:'earth',title:'地層の新旧',level:'standard',seconds:70,stimulus:['露頭','diagram_text','地層は逆転していない。火山灰層Kの下に砂岩P、上に泥岩Qがある。'],stem:'PとQの新旧関係を選びなさい。',answer:'Pの方がQより古い。',wrong:[['Qの方がPより古い。','sequence_error','逆転していないので下位が古いです。'],['PとQは必ず同時にできた。','scope_overreach','上下に異なる層です。'],['Kがあるので判断できない。','condition_omission','上下関係から判断できます。']],explanation:'逆転がなければ下位ほど古いためPが古いです。',steps:['逆転なしを確認。','上下関係を適用。'],skills:['sci.earth.strata']}))],
 ['earth_astronomy','earth',s=>single({seed:s,key:'earth_astronomy',domain:'earth',title:'日周運動',stimulus:['観察','data','同じ星が3時間で空を西向きに約45°移動して見えた。'],stem:'この見かけの動きの主な原因を選びなさい。',answer:'地球が西から東へ自転しているため。',wrong:[['地球が東から西へ自転しているため。','sign_direction','自転方向が逆です。'],['星が3時間で地球を一周するため。','concept_confusion','日周運動の主因は地球の自転です。'],['地球の公転だけで数時間ごとに大きく動くため。','concept_confusion','数時間スケールは自転で説明します。']],explanation:'地球が西から東へ自転するため、天体は反対向きの東から西へ動くように見えます。',steps:['見かけの方向を確認。','観測者である地球の回転を考える。'],skills:['sci.earth.astronomy','sci.earth.reference_frame']}))]
];
const byDomain=Object.freeze(PROFILE.domains.reduce((m,d)=>(m[d]=T.filter(x=>x[1]===d),m),{}));
export function buildExam(seed='science-exam'){const questions=T.map((x,i)=>x[2](seed+':'+i));return assertExam({schemaVersion:1,id:'science-exam-'+hashSeed(seed).toString(36),title:'愛知県型 理科 22点実戦',profileId:PROFILE.id,nonOfficial:true,seed:String(seed),questions});}
export function generateQuestion({seed=String(Date.now())+Math.random(),domain=null}={}){const r=seededRandom(seed+':pick');let d=domain;if(!PROFILE.domains.includes(d)){const x=r(),w=PROFILE.targetWeights;d=x<w.biology?'biology':x<w.biology+w.earth?'earth':x<w.biology+w.earth+w.physics?'physics':'chemistry';}const p=byDomain[d],x=p[Math.floor(r()*p.length)];return x[2](seed+':'+x[0]);}
export function templateCounts(){return Object.fromEntries(PROFILE.domains.map(d=>[d,byDomain[d].length]));}
