(()=>{'use strict';
const app=document.getElementById('app');
if(!app||window.__RISE_UI_V4__)return;
window.__RISE_UI_V4__={version:'4.2.0',structure:'complete'};
const root=document.documentElement;
root.dataset.riseUi='4';root.dataset.riseSkin='v4';root.dataset.riseStructure='optimized-4';
const pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const dayKey=(ts=Date.now())=>{const d=new Date(ts);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtDate=()=>{const d=new Date();return `${d.getMonth()+1}月${d.getDate()}日 ${['日','月','火','水','木','金','土'][d.getDay()]}曜日`};
const subjectNames={english:'英語',japanese:'国語',math:'数学',science:'理科',social:'社会'};
const subjectKeys=['english','math','japanese','science','social'];
const subjectIcons={english:'A',math:'√',japanese:'文',science:'△',social:'◎'};
const icon=name=>({
 home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10.5 12 4l8 6.5v8a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 4 18.5z"/><path d="M9 20v-6h6v6"/></svg>',
 study:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4.5 5.5A2.5 2.5 0 0 1 7 3h5v17H7a2.5 2.5 0 0 0-2.5 2z"/><path d="M19.5 5.5A2.5 2.5 0 0 0 17 3h-5v17h5a2.5 2.5 0 0 1 2.5 2z"/></svg>',
 review:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11a8 8 0 1 0-2.4 5.7"/><path d="M20 5v6h-6"/></svg>',
 record:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19V9m7 10V4m7 15v-7"/></svg>',
 settings:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h10M18 7h2M4 17h3m4 0h9M14 4v6M7 14v6"/></svg>',
 arrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>'
})[name]||'';
function getState(){try{return window.AA_APP?.get?.('state')?.get?.()||null}catch(_){return null}}
function inferRoute(s){if(s?.route)return s.route;const active=document.querySelector('.nav [data-route].active');return active?.dataset?.route||root.dataset.riseRoute||'home'}
function fallbackState(route){return {route,items:{},stats:{days:{}},profile:{grammarGate:{}},ui:{subjectDifficulty:6}}}
function streak(days){let n=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<366;i++){const k=dayKey(d.getTime());if(Number(days?.[k]?.attempts||0)>0){n++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return n}
function due(items){const now=Date.now();return Object.values(items||{}).reduce((n,x)=>n+(Number(x?.dueAt||0)>0&&Number(x.dueAt)<=now?1:0),0)}
function retention(items){const now=Date.now(),DAY=86400000,arr=Object.values(items||{}).filter(x=>Number(x?.lastReviewAt||0)>0);if(!arr.length)return null;let kept=0;for(const x of arr){const age=Math.max(0,(now-Number(x.lastReviewAt))/DAY),st=Math.max(.18,Number(x.stabilityDays||.5));if(Math.exp(-age/st)>=.65)kept++}return Math.round(kept/arr.length*100)}
function readiness(){const n=Number((app.querySelector('.scoreRing b')?.textContent||'').trim());return Number.isFinite(n)?Math.max(0,Math.min(100,n)):null}
function mission(){const title=app.querySelector('.missionTitle')?.textContent?.trim()||'おすすめ学習';return title.replace(/^今いちばん合格力に効く[：:]\s*/,'')}
function missionWhy(){return app.querySelector('.missionWhy')?.textContent?.trim()?.replace(/。問題数ではなく、.*$/,'')||'弱点・忘却・入試重要度から次の学習を選びます。'}
function subjectScores(){const found={};for(const r of app.querySelectorAll('.barLine')){const label=r.querySelector('label')?.textContent?.trim();const key=Object.keys(subjectNames).find(k=>subjectNames[k]===label);if(!key||found[key])continue;const raw=(r.querySelector('output')?.textContent||'').trim();const n=Number(raw);found[key]=Number.isFinite(n)?Math.max(0,Math.min(100,n)):null}return subjectKeys.map(key=>({key,name:subjectNames[key],score:key in found?found[key]:null}))}
function week(days){const out=[],d=new Date();d.setHours(12,0,0,0);for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);const v=days?.[dayKey(x.getTime())]||{};out.push({label:['日','月','火','水','木','金','土'][x.getDay()],minutes:Math.round(Number(v.ms||0)/60000),attempts:Number(v.attempts||0),correct:Number(v.correct||0)})}return out}
function chart(data){const W=560,H=126,max=Math.max(20,...data.map(x=>x.minutes)),pts=data.map((x,i)=>[12+i*89,H-18-(x.minutes/max)*88]),line=pts.map(p=>p.join(',')).join(' ');return `<div class="rv4Chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="直近7日間の学習時間"><defs><linearGradient id="rv4line" x1="0" x2="1"><stop offset="0" stop-color="#7fb7ff"/><stop offset=".52" stop-color="#a77dff"/><stop offset="1" stop-color="#f29bcf"/></linearGradient></defs><line x1="12" y1="96" x2="546" y2="96"/><line x1="12" y1="58" x2="546" y2="58"/><polyline points="${line}"/>${pts.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3"/>`).join('')}</svg><div>${data.map(x=>`<span>${x.label}</span>`).join('')}</div></div>`}
function statusText(n){return n==null?'測定中':n>=75?'良好':n>=55?'伸びしろ':'優先'}
function weakest(sub){return sub.filter(x=>x.score!=null).sort((a,b)=>a.score-b.score)[0]||sub[0]}
function todayPlan(s){const reviewDue=due(s.items),sub=subjectScores(),weak=weakest(sub);return [
 {tag:'最優先',title:mission(),note:missionWhy(),action:'<button class="rv4PlanAction" data-action="start-mission">開始</button>'},
 {tag:'復習',title:reviewDue?`${reviewDue}項目を回収`:'復習キューを確認',note:reviewDue?'期限が来た項目を先に戻します。':'忘却が進む前に復習状況を確認します。',action:'<a class="rv4PlanAction" href="./review/">開く</a>'},
 {tag:'弱点',title:`${weak.name}を補強`,note:weak.score==null?'測定データを増やして弱点を特定します。':`現在地 ${weak.score}% · 低い領域から短く補強します。`,action:'<button class="rv4PlanAction" data-route="subjects">選ぶ</button>'}
]}
function metricCard(title,value,unit,status,type){const numeric=value!=null;const p=numeric?Math.max(0,Math.min(100,Number(value))):0;return `<article class="rv4Metric rv4Card"><div class="rv4CardHead"><h3>${title}</h3><span>${status}</span></div><div class="rv4MetricBody"><div><strong>${numeric?value:'--'}</strong><small>${numeric?unit:''}</small><p>${numeric?status:'学習データを集めています'}</p></div><div class="${type==='retention'?'rv4Donut':'rv4Ring'}" style="--v:${p};--a:${Math.min(p,46)};--b:${Math.min(100,Math.max(p,46)+30)}"></div></div></article>`}
function homeHTML(s){const today=s.stats?.days?.[dayKey()]||{},attempts=Number(today.attempts||0),accuracy=attempts?Math.round(Number(today.correct||0)/attempts*100):null,ready=readiness(),mem=retention(s.items),reviewDue=due(s.items),run=streak(s.stats?.days||{}),sub=subjectScores(),w=week(s.stats?.days||{}),weekMin=w.reduce((a,x)=>a+x.minutes,0),plan=todayPlan(s);return `<section class="riseHomeV4" data-ui-ver="4.2.0"><header class="rv4Welcome"><span>RISE / LEARNING DASHBOARD</span><h2>今日の一歩を、合格力に。</h2><p>${esc(fmtDate())} · ${attempts?`${attempts}問完了${accuracy==null?'':` / 正答率 ${accuracy}%`}`:'まずは最優先の1つから'}</p></header><div class="rv4Dashboard"><div class="rv4Metrics">${metricCard('旭丘 Readiness',ready,'/100',statusText(ready),'ready')}${metricCard('記憶の定着度',mem,'%',statusText(mem),'retention')}</div><article class="rv4Plan rv4Card"><div class="rv4CardHead"><div><span class="rv4Kicker">TODAY</span><h3>今日の学習</h3></div><span>${reviewDue?`復習 ${reviewDue}件`:'優先順'}</span></div><div class="rv4PlanList">${plan.map(x=>`<div class="rv4PlanRow"><b>${x.tag}</b><div><strong>${esc(x.title)}</strong><span>${esc(x.note)}</span></div>${x.action}</div>`).join('')}</div><button class="btn primary rv4Start" data-action="start-mission">学習を開始する ${icon('arrow')}</button></article><article class="rv4SubjectsCard rv4Card"><div class="rv4CardHead"><h3>教科別の達成度</h3><button class="rv4TextButton" data-route="subjects">学習へ</button></div><div class="rv4Subjects">${sub.map(x=>`<div><i>${subjectIcons[x.key]}</i><b>${x.name}</b><span><u style="width:${x.score??0}%"></u></span><em>${x.score==null?'--':x.score+'%'}</em></div>`).join('')}</div></article><article class="rv4Week rv4Card"><div class="rv4CardHead"><h3>今週の学習状況</h3><button class="rv4TextButton" data-route="analytics">記録へ</button></div><div class="rv4WeekTotal"><strong>${weekMin>=60?(weekMin/60).toFixed(1):weekMin}</strong><span>${weekMin>=60?'時間':'分'}</span><small>${attempts?`今日は${attempts}問`:'今日の記録はまだありません'}</small></div>${chart(w)}</article><article class="rv4StreakCard rv4Card"><div class="rv4CardHead"><h3>連続学習</h3><span>STREAK</span></div><div class="rv4StreakHero"><i>✦</i><strong>${run}</strong><span>日</span></div><p>${run?`${run}日連続で前進中`:'今日から記録をつなげよう'}</p><div class="rv4MiniStats"><span><b>${attempts}</b>今日の問題</span><span><b>${accuracy==null?'--':accuracy+'%'}</b>今日の正答率</span></div></article></div></section>`}
function subjectAction(x){if(x.key==='english')return '<button class="btn primary" data-action="start-custom" data-kind="reading" data-subject="english">長文を始める</button>';if(x.key==='japanese')return '<button class="btn primary" data-action="start-custom" data-kind="kanji" data-subject="japanese">国語を始める</button>';return `<button class="btn primary" data-action="start-custom" data-kind="subject" data-subject="${x.key}">${x.name}を始める</button>`}
function subjectsHTML(s){const sub=subjectScores(),diff=Number(s.ui?.subjectDifficulty||6);return `<section class="riseSubjectsV4" data-ui-ver="4.2.0"><div class="rv4PageTitle"><span>STUDY</span><h2>学習を始める</h2><p>おすすめ、入試実戦、教科別。目的から最短で開始できます。</p></div><article class="rv4StudyHero rv4Card"><div><span class="rv4Kicker">RECOMMENDED</span><h3>${esc(mission())}</h3><p>${esc(missionWhy())}</p></div><button class="btn primary" data-action="start-mission">おすすめを開始 ${icon('arrow')}</button></article><div class="rv4StudyQuick"><button class="rv4ModeCard" data-action="start-mixed"><i>25</i><div><b>5教科ミックス</b><span>実戦25問・非公式</span></div>${icon('arrow')}</button><button class="rv4ModeCard" data-action="start-review"><i>↻</i><div><b>間違い直し</b><span>別表面で再出題</span></div>${icon('arrow')}</button><button class="rv4ModeCard" data-action="start-reading-simulator"><i>40</i><div><b>愛知英語 40分</b><span>筆記シミュレーター</span></div>${icon('arrow')}</button></div><div class="rv4SubjectGrid">${sub.map(x=>`<article class="rv4SubjectCard rv4Card"><div class="rv4SubjectTop"><i>${subjectIcons[x.key]}</i><div><span>${x.score==null?'測定中':`現在地 ${x.score}%`}</span><h3>${x.name}</h3></div><em>${statusText(x.score)}</em></div><div class="rv4SubjectProgress"><span><u style="width:${x.score??0}%"></u></span></div>${subjectAction(x)}${x.key==='english'?'<div class="rv4SubjectExtras"><button data-action="start-reading-exam">入試長文</button><button data-action="start-custom" data-kind="vocab" data-subject="english">英単語</button></div>':''}${x.key==='social'?'<div class="rv4SubjectExtras"><button data-route="timeline">歴史年表</button></div>':''}</article>`).join('')}</div><details class="rv4Difficulty rv4Card"><summary><div><b>演習難度</b><span>Level ${diff}</span></div><em>調整</em></summary><div class="rv4DifficultyBody"><input type="range" min="1" max="11" value="${diff}" data-action="difficulty"><p>未履修範囲は勝手に解禁せず、問題の深さや情報量で難度を調整します。</p></div></details></section>`}
function aggregate(days,limit=30){const keys=Object.keys(days||{}).sort().slice(-limit);let attempts=0,correct=0,ms=0;for(const k of keys){const d=days[k]||{};attempts+=Number(d.attempts||0);correct+=Number(d.correct||0);ms+=Number(d.ms||0)}return {attempts,correct,minutes:Math.round(ms/60000),accuracy:attempts?Math.round(correct/attempts*100):null}}
function analyticsHTML(s){const ready=readiness(),mem=retention(s.items),w=week(s.stats?.days||{}),weekAgg={attempts:w.reduce((a,x)=>a+x.attempts,0),correct:w.reduce((a,x)=>a+x.correct,0),minutes:w.reduce((a,x)=>a+x.minutes,0)},month=aggregate(s.stats?.days||{},30),sub=subjectScores(),run=streak(s.stats?.days||{});const weekAcc=weekAgg.attempts?Math.round(weekAgg.correct/weekAgg.attempts*100):null;return `<section class="riseAnalyticsV4" data-ui-ver="4.2.0"><div class="rv4PageTitle"><span>RECORD</span><h2>学習記録</h2><p>数字を眺めるためではなく、次に何をするか決めるための記録です。</p></div><div class="rv4RecordHero"><article class="rv4Card"><span>直近7日</span><strong>${weekAgg.minutes>=60?(weekAgg.minutes/60).toFixed(1):weekAgg.minutes}</strong><small>${weekAgg.minutes>=60?'時間':'分'}</small><p>${weekAgg.attempts}問 · 正答率 ${weekAcc==null?'--':weekAcc+'%'}</p></article><article class="rv4Card"><span>30日</span><strong>${month.attempts}</strong><small>問</small><p>正答率 ${month.accuracy==null?'--':month.accuracy+'%'}</p></article><article class="rv4Card"><span>連続</span><strong>${run}</strong><small>日</small><p>学習ストリーク</p></article><article class="rv4Card"><span>定着</span><strong>${mem==null?'--':mem}</strong><small>${mem==null?'':'%'}</small><p>Readiness ${ready==null?'測定中':ready+'/100'}</p></article></div><div class="rv4RecordGrid"><article class="rv4Week rv4Card"><div class="rv4CardHead"><h3>学習時間</h3><span>直近7日</span></div>${chart(w)}</article><article class="rv4Card"><div class="rv4CardHead"><h3>教科別の現在地</h3><button class="rv4TextButton" data-route="subjects">補強する</button></div><div class="rv4Subjects">${sub.map(x=>`<div><i>${subjectIcons[x.key]}</i><b>${x.name}</b><span><u style="width:${x.score??0}%"></u></span><em>${x.score==null?'--':x.score+'%'}</em></div>`).join('')}</div></article></div></section>`}
function grammarLabel(k){return {basic:'基本文',past:'過去',future:'未来',modal:'助動詞',infinitive:'不定詞',gerund:'動名詞',comparison:'比較',passive:'受け身',presentPerfect:'現在完了',asMuchAs:'as much ... as',asManyAs:'as many ... as',participle:'分詞',relativePronoun:'関係代名詞',indirectQuestion:'間接疑問',presentPerfectProgressive:'現在完了進行形',subjunctive:'仮定法'}[k]||k}
function settingsHTML(s){const gate=s.profile?.grammarGate||{};return `<section class="riseSettingsV4" data-ui-ver="4.2.0"><div class="rv4PageTitle"><span>SETTINGS</span><h2>設定</h2><p>学習に必要な項目だけ残しています。</p></div><article class="rv4SettingsCard"><details><summary><div><b>英語の学習範囲</b><span>未履修文法を長文から除外</span></div><em>変更</em></summary><div class="rv4SettingsBody">${Object.entries(gate).map(([k,v])=>`<label class="switch"><span>${esc(grammarLabel(k))}</span><input type="checkbox" data-action="grammar" data-key="${esc(k)}" ${v?'checked':''}></label>`).join('')||'<p class="sub">文法範囲を読み込んでいます。</p>'}</div></details></article><article class="rv4SettingsCard"><details><summary><div><b>バックアップ</b><span>端末変更やSafariデータ削除に備える</span></div><em>開く</em></summary><div class="rv4SettingsBody"><div class="actions"><button class="btn soft" data-action="export">JSONを書き出す</button><button class="btn ghost" data-action="import-open">JSONを読み込む</button><button class="btn ghost" data-action="copy-backup">テキスト表示</button></div><p class="tiny">学習履歴は端末内に自動保存されます。</p></div></details></article><article class="rv4SettingsCard rv4DangerZone"><details><summary><div><b>学習データを初期化</b><span>履歴・習熟度をすべて削除</span></div><em>注意</em></summary><div class="rv4SettingsBody"><button class="btn danger" data-action="reset">全学習データを初期化</button></div></details></article></section>`}
function decorateBrand(){const brand=app.querySelector('.brand');if(!brand)return;const mark=brand.querySelector('.mark'),h=brand.querySelector('h1'),p=brand.querySelector('p');if(mark)mark.textContent='R';if(h)h.textContent='Rise';if(p)p.textContent='旭丘合格のための学習OS'}
function decorateTop(route){const box=app.querySelector('.topBtns');if(!box)return;const target=route==='settings'?'home':'settings',sig=`menu:${target}`;if(box.dataset.riseTop===sig)return;box.dataset.riseTop=sig;box.innerHTML=`<button class="iconBtn rv4MenuBtn" data-route="${target}" aria-label="${route==='settings'?'設定を閉じる':'設定を開く'}">${route==='settings'?'×':icon('settings')}</button>`}
function navRoute(route){return ['subjects','mission','study','timeline'].includes(route)?'subjects':route==='analytics'?'analytics':'home'}
function navHTML(route){const r=navRoute(route),active=x=>r===x?'active':'';return `<button class="${active('home')}" data-route="home" aria-label="ホーム"><b>${icon('home')}</b><span>ホーム</span></button><button class="${active('subjects')}" data-route="subjects" aria-label="入試"><b>${icon('study')}</b><span>入試</span></button><button class="${active('analytics')}" data-route="analytics" aria-label="学習"><b>${icon('record')}</b><span>学習</span></button><a href="./review/" aria-label="復習"><b>${icon('review')}</b><span>復習</span></a>`}
function decorateNav(route){const nav=document.querySelector('.nav');if(!nav)return;let inner=nav.querySelector('.navin');if(!inner){inner=document.createElement('div');inner.className='navin';nav.replaceChildren(inner)}const sig=`complete:${navRoute(route)}`;if(inner.dataset.riseNav===sig)return;inner.dataset.riseNav=sig;inner.innerHTML=navHTML(route)}
function replacePanel(main,selector,html){let panel=main.querySelector(selector);if(!panel){main.insertAdjacentHTML('afterbegin',html);return}if(panel.dataset.uiVer!=='4.2.0')panel.outerHTML=html}
function decorateRoute(s){const route=inferRoute(s);root.dataset.riseRoute=route;decorateBrand();decorateTop(route);decorateNav(route);const main=app.querySelector('main');if(!main)return;if(route==='home')replacePanel(main,'.riseHomeV4',homeHTML(s));if(route==='subjects')replacePanel(main,'.riseSubjectsV4',subjectsHTML(s));if(route==='analytics')replacePanel(main,'.riseAnalyticsV4',analyticsHTML(s));if(route==='settings')replacePanel(main,'.riseSettingsV4',settingsHTML(s))}
let busy=false,raf=0;function run(){if(busy)return;busy=true;observer.disconnect();try{const live=getState(),route=inferRoute(live);decorateRoute(live||fallbackState(route))}finally{busy=false;observer.observe(app,{childList:true,subtree:true})}}
const observer=new MutationObserver(()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(run)});observer.observe(app,{childList:true,subtree:true});requestAnimationFrame(run);addEventListener('pageshow',()=>requestAnimationFrame(run));document.addEventListener('aa:v23ready',()=>requestAnimationFrame(run));let tries=0;const bootTimer=setInterval(()=>{tries++;requestAnimationFrame(run);if(getState()||tries>=40)clearInterval(bootTimer)},250);
})();
