(()=>{'use strict';
const app=document.getElementById('app');
if(!app||window.__RISE_UI_V4__)return;
window.__RISE_UI_V4__={version:'4.1.0',structure:'optimized'};
const root=document.documentElement;
root.dataset.riseUi='4';
root.dataset.riseSkin='v4';
root.dataset.riseStructure='optimized-4';
const pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const dayKey=(ts=Date.now())=>{const d=new Date(ts);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtDate=()=>{const d=new Date();return `${d.getMonth()+1}月${d.getDate()}日 ${['日','月','火','水','木','金','土'][d.getDay()]}曜日`};
const subjectIcons={英語:'A',数学:'√',国語:'文',理科:'△',社会:'◎'};
function icon(name){const common='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';const p={home:'<path d="M3 10.8 12 3l9 7.8"/><path d="M5.5 9.8V21h13V9.8"/><path d="M9.5 21v-7h5v7"/>',study:'<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5a2.5 2.5 0 0 1 2.5 2.5z"/>',review:'<path d="M4 12a8 8 0 1 0 2.4-5.7L4 8.7"/><path d="M4 4v4.7h4.7"/><path d="M12 7v5l3 2"/>',record:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.86 2.86-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.1A1.7 1.7 0 0 0 8.2 19.3a1.7 1.7 0 0 0-1.88.34l-.06.06-2.86-2.86.06-.06A1.7 1.7 0 0 0 3.8 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H2V9.6h.1A1.7 1.7 0 0 0 3.7 8.2a1.7 1.7 0 0 0-.34-1.88l-.06-.06L6.16 3.4l.06.06A1.7 1.7 0 0 0 8.1 3.8a1.7 1.7 0 0 0 1-.6A1.7 1.7 0 0 0 9.5 2.1V2h4v.1a1.7 1.7 0 0 0 1.4 1.6 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.86 2.86-.06.06A1.7 1.7 0 0 0 19.3 8.1a1.7 1.7 0 0 0 .6 1 1.7 1.7 0 0 0 1.1.4h.1v4H21a1.7 1.7 0 0 0-1.6 1.4Z"/>')[name]||'<circle cx="12" cy="12" r="8"/>';return `<svg ${common}>${p}</svg>`}
function getState(){try{return window.AA_APP?.get?.('state')?.get?.()||null}catch(_){return null}}
function inferRoute(s){if(s?.route)return s.route;const active=document.querySelector('.nav [data-route].active');return active?.dataset?.route||root.dataset.riseRoute||'home'}
function fallbackState(route){return {route,items:{},stats:{days:{}},profile:{grammarGate:{}},theme:'light'}}
function streak(days){let n=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<366;i++){const k=dayKey(d.getTime());if(Number(days?.[k]?.attempts||0)>0){n++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return n}
function due(items){const now=Date.now();return Object.values(items||{}).reduce((n,x)=>n+(Number(x?.dueAt||0)>0&&Number(x.dueAt)<=now?1:0),0)}
function retention(items){const now=Date.now(),DAY=86400000,arr=Object.values(items||{}).filter(x=>Number(x?.lastReviewAt||0)>0);if(!arr.length)return {score:null,strong:0,mid:0,review:0};let a=0,b=0,c=0;for(const x of arr){const age=Math.max(0,(now-Number(x.lastReviewAt))/DAY),st=Math.max(.18,Number(x.stabilityDays||.5)),r=Math.exp(-age/st);if(r>=.85)a++;else if(r>=.65)b++;else c++}const t=arr.length,strong=Math.round(a/t*100),mid=Math.round(b/t*100),review=Math.max(0,100-strong-mid);return {score:Math.round((a+b)/t*100),strong,mid,review}}
function readiness(){const el=app.querySelector('.scoreRing b');const n=Number((el?.textContent||'').trim());return Number.isFinite(n)?Math.max(0,Math.min(100,n)):null}
function mission(){const title=app.querySelector('.missionTitle')?.textContent?.trim()||'おすすめ学習';return title.replace(/^今いちばん合格力に効く[：:]\s*/,'')}
function missionWhy(){return app.querySelector('.missionWhy')?.textContent?.trim()?.replace(/。問題数ではなく、.*$/,'')||'弱点・忘却・入試重要度から優先しています。'}
function subjects(){const wanted=['英語','数学','国語','理科','社会'],rows=[];for(const r of app.querySelectorAll('.barLine')){const name=r.querySelector('label')?.textContent?.trim();if(!wanted.includes(name)||rows.some(x=>x.name===name))continue;const n=Number((r.querySelector('output')?.textContent||'').trim());rows.push({name,score:Number.isFinite(n)?Math.max(0,Math.min(100,n)):null})}return wanted.map(name=>rows.find(x=>x.name===name)||{name,score:null})}
function week(days){const out=[],d=new Date();d.setHours(12,0,0,0);for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);const v=days?.[dayKey(x.getTime())]||{};out.push({label:['日','月','火','水','木','金','土'][x.getDay()],minutes:Math.round(Number(v.ms||0)/60000)})}return out}
function chart(data){const W=560,H=118,max=Math.max(20,...data.map(x=>x.minutes)),pts=data.map((x,i)=>[10+i*90,H-14-(x.minutes/max)*88]),line=pts.map(p=>p.join(',')).join(' ');return `<div class="rv4Chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="直近7日間の学習時間"><defs><linearGradient id="rv4line" x1="0" x2="1"><stop offset="0" stop-color="#78b8ff"/><stop offset=".55" stop-color="#a984ff"/><stop offset="1" stop-color="#f098cf"/></linearGradient></defs><line x1="10" y1="94" x2="550" y2="94"/><line x1="10" y1="56" x2="550" y2="56"/><polyline points="${line}"/></svg><div>${data.map(x=>`<span>${x.label}</span>`).join('')}</div></div>`}
function homeHTML(s){const today=s.stats?.days?.[dayKey()]||{},attempts=Number(today.attempts||0),accuracy=attempts?Math.round(Number(today.correct||0)/attempts*100):null,ready=readiness(),mem=retention(s.items),reviewDue=due(s.items),run=streak(s.stats?.days||{}),sub=subjects(),w=week(s.stats?.days||{}),weekMin=w.reduce((a,x)=>a+x.minutes,0);return `<section class="riseHomeV4"><header class="rv4Welcome"><div><span>RISE / TODAY</span><h2>今日やることを、迷わない。</h2><p>${esc(fmtDate())} · ${attempts?`${attempts}問完了${accuracy==null?'':` / 正答率${accuracy}%`}`:'最優先の1つから始めよう'}</p></div></header><article class="rv4Focus"><div class="rv4FocusCopy"><span>NEXT BEST ACTION</span><h3>${esc(mission())}</h3><p>${esc(missionWhy())}</p><div class="rv4FocusActions"><button class="btn primary" data-action="start-mission">今すぐ始める</button><button class="btn ghost" data-route="mission">選定理由</button></div></div><div class="rv4FocusBadge"><b>${reviewDue}</b><span>復習待ち</span></div></article><div class="rv4Quick"><a class="rv4QuickItem" href="./review/"><i>${icon('review')}</i><div><b>復習</b><span>${reviewDue?`${reviewDue}項目が期限`:'今は期限なし'}</span></div><em>›</em></a><button class="rv4QuickItem" data-route="subjects"><i>${icon('study')}</i><div><b>学習メニュー</b><span>5教科・入試演習</span></div><em>›</em></button></div><div class="rv4Snapshot"><article><span>今日</span><strong>${attempts}</strong><small>問</small></article><article><span>連続</span><strong>${run}</strong><small>日</small></article><article><span>Readiness</span><strong>${ready==null?'--':ready}</strong><small>${ready==null?'':'/100'}</small></article><article><span>定着</span><strong>${mem.score==null?'--':mem.score}</strong><small>${mem.score==null?'':'%'}</small></article></div><div class="rv4MainGrid rv4MainGridOptimized"><article class="rv4Card"><div class="rv4CardHead"><h3>5教科の現在地</h3><button class="rv4TextButton" data-route="subjects">学習へ</button></div><div class="rv4Subjects">${sub.map(x=>`<div><i>${subjectIcons[x.name]}</i><b>${x.name}</b><span><u style="width:${x.score??0}%"></u></span><em>${x.score==null?'--':x.score+'%'}</em></div>`).join('')}</div></article><article class="rv4Card rv4Week"><div class="rv4CardHead"><h3>直近7日</h3><button class="rv4TextButton" data-route="analytics">記録を見る</button></div><div class="rv4WeekTotal"><strong>${weekMin>=60?(weekMin/60).toFixed(1):weekMin}</strong><span>${weekMin>=60?'時間':'分'}</span><small>${attempts?`今日は${attempts}問`:'今日の記録はまだありません'}</small></div>${chart(w)}</article></div></section>`}
function analyticsHTML(s){const ready=readiness(),w=week(s.stats?.days||{}),mins=w.reduce((a,x)=>a+x.minutes,0),mem=retention(s.items);return `<section class="riseAnalyticsV4"><div class="rv4PageTitle"><span>RECORD</span><h2>学習記録</h2><p>次の学習判断に必要な数字だけを表示します。</p></div><div class="rv4Snapshot rv4RecordSnapshot"><article><span>Readiness</span><strong>${ready==null?'--':ready}</strong><small>${ready==null?'':'/100'}</small></article><article><span>定着</span><strong>${mem.score==null?'--':mem.score}</strong><small>${mem.score==null?'':'%'}</small></article><article><span>7日間</span><strong>${mins>=60?(mins/60).toFixed(1):mins}</strong><small>${mins>=60?'時間':'分'}</small></article></div><article class="rv4Card rv4Week"><div class="rv4CardHead"><h3>学習時間</h3><span>直近7日</span></div>${chart(w)}</article></section>`}
function grammarLabel(k){return {basic:'基本文',past:'過去',future:'未来',modal:'助動詞',infinitive:'不定詞',gerund:'動名詞',comparison:'比較',passive:'受け身',presentPerfect:'現在完了',asMuchAs:'as much ... as',asManyAs:'as many ... as',participle:'分詞',relativePronoun:'関係代名詞',indirectQuestion:'間接疑問',presentPerfectProgressive:'現在完了進行形',subjunctive:'仮定法'}[k]||k}
function settingsHTML(s){const gate=s.profile?.grammarGate||{},theme=s.theme||root.dataset.theme||'light';return `<section class="riseSettingsV4"><div class="rv4PageTitle"><span>SETTINGS</span><h2>設定</h2><p>学習に必要な設定だけに絞っています。</p></div><article class="rv4SettingsCard"><div class="rv4SettingsHead"><div><b>表示</b><span>画面の明るさ</span></div><button class="btn ghost" data-action="theme">${theme==='dark'?'ライトへ':'ダークへ'}</button></div></article><article class="rv4SettingsCard"><details><summary><div><b>英語の学習範囲</b><span>未履修文法を長文から除外</span></div><em>変更</em></summary><div class="rv4SettingsBody">${Object.entries(gate).map(([k,v])=>`<label class="switch"><span>${esc(grammarLabel(k))}</span><input type="checkbox" data-action="grammar" data-key="${esc(k)}" ${v?'checked':''}></label>`).join('')||'<p class="sub">文法範囲を読み込んでいます。</p>'}</div></details></article><article class="rv4SettingsCard"><details><summary><div><b>バックアップ</b><span>端末変更やSafariデータ削除に備える</span></div><em>開く</em></summary><div class="rv4SettingsBody"><div class="actions"><button class="btn soft" data-action="export">JSONを書き出す</button><button class="btn ghost" data-action="import-open">JSONを読み込む</button><button class="btn ghost" data-action="copy-backup">テキスト表示</button></div><p class="tiny">学習履歴は端末内に自動保存されます。</p></div></details></article><article class="rv4SettingsCard rv4DangerZone"><details><summary><div><b>データを初期化</b><span>学習履歴・習熟度をすべて削除</span></div><em>注意</em></summary><div class="rv4SettingsBody"><button class="btn danger" data-action="reset">全学習データを初期化</button></div></details></article></section>`}
function decorateBrand(){const brand=app.querySelector('.brand');if(!brand)return;const mark=brand.querySelector('.mark'),h=brand.querySelector('h1'),p=brand.querySelector('p');if(mark)mark.textContent='R';if(h)h.textContent='Rise';if(p)p.textContent='旭丘合格のための学習OS'}
function navHTML(route){const active=r=>route===r?'active':'';return `<button class="${active('home')}" data-route="home" aria-label="ホーム"><b>${icon('home')}</b><span>ホーム</span></button><button class="${active('subjects')}" data-route="subjects" aria-label="学習"><b>${icon('study')}</b><span>学習</span></button><a href="./review/" aria-label="復習"><b>${icon('review')}</b><span>復習</span></a><button class="${active('analytics')}" data-route="analytics" aria-label="記録"><b>${icon('record')}</b><span>記録</span></button>`}
function decorateNav(route){const nav=document.querySelector('.nav');if(!nav)return;let inner=nav.querySelector('.navin');if(!inner){inner=document.createElement('div');inner.className='navin';nav.replaceChildren(inner)}const sig=`optimized:${route}`;if(inner.dataset.riseNav===sig)return;inner.dataset.riseNav=sig;inner.innerHTML=navHTML(route)}
function hydratePanel(main,selector,html,hydrated){let panel=main.querySelector(selector);if(!panel){main.insertAdjacentHTML('afterbegin',html);panel=main.querySelector(selector);if(panel)panel.dataset.hydrated=hydrated?'1':'0'}else if(hydrated&&panel.dataset.hydrated!=='1'){panel.outerHTML=html;panel=main.querySelector(selector);if(panel)panel.dataset.hydrated='1'}return panel}
function decorateRoute(s,hydrated){const route=inferRoute(s);root.dataset.riseUi='4';root.dataset.riseSkin='v4';root.dataset.riseStructure='optimized-4';root.dataset.riseRoute=route;decorateBrand();decorateNav(route);const main=app.querySelector('main');if(!main)return;if(route==='home')hydratePanel(main,'.riseHomeV4',homeHTML(s),hydrated);if(route==='analytics'){const first=main.querySelector(':scope > section.card');if(first)first.classList.add('rv4LegacyLead');hydratePanel(main,'.riseAnalyticsV4',analyticsHTML(s),hydrated)}if(route==='settings')hydratePanel(main,'.riseSettingsV4',settingsHTML(s),hydrated)}
let busy=false,raf=0;function run(){if(busy)return;busy=true;observer.disconnect();try{decorateBrand();const live=getState();const route=inferRoute(live);decorateRoute(live||fallbackState(route),!!live)}finally{busy=false;observer.observe(app,{childList:true,subtree:true})}}
const observer=new MutationObserver(()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(run)});observer.observe(app,{childList:true,subtree:true});requestAnimationFrame(run);addEventListener('pageshow',()=>requestAnimationFrame(run));document.addEventListener('aa:v23ready',()=>requestAnimationFrame(run));let tries=0;const bootTimer=setInterval(()=>{tries++;requestAnimationFrame(run);if(getState()||tries>=40)clearInterval(bootTimer)},250);
})();