(()=>{'use strict';
const app=document.getElementById('app');
if(!app||window.__RISE_UI_V4__)return;
window.__RISE_UI_V4__=true;
const root=document.documentElement;
const pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const dayKey=(ts=Date.now())=>{const d=new Date(ts);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtDate=()=>{const d=new Date();return `${d.getMonth()+1}月${d.getDate()}日 ${['日','月','火','水','木','金','土'][d.getDay()]}曜日`};
const routeMeta={home:['HOME','home'],mission:['今日','target'],subjects:['演習','grid'],exam:['入試','exam'],mock:['入試','exam'],tests:['入試','exam'],analytics:['分析','chart'],settings:['設定','settings']};
const subjectIcons={英語:'A',数学:'√',国語:'文',理科:'△',社会:'◎'};
function icon(name){const common='viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"';const p={home:'<path d="M3 10.8 12 3l9 7.8"/><path d="M5.5 9.8V21h13V9.8"/><path d="M9.5 21v-7h5v7"/>',target:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M22 12h-3"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',exam:'<path d="M7 3h10v4H7z"/><path d="M5 5h14v16H5z"/><path d="M8 11h8M8 15h8"/>',chart:'<path d="M4 20V10M10 20V4M16 20v-7M22 20V8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.86 2.86-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.1A1.7 1.7 0 0 0 8.2 19.3a1.7 1.7 0 0 0-1.88.34l-.06.06-2.86-2.86.06-.06A1.7 1.7 0 0 0 3.8 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H2V9.6h.1A1.7 1.7 0 0 0 3.7 8.2a1.7 1.7 0 0 0-.34-1.88l-.06-.06L6.16 3.4l.06.06A1.7 1.7 0 0 0 8.1 3.8a1.7 1.7 0 0 0 1-.6A1.7 1.7 0 0 0 9.5 2.1V2h4v.1a1.7 1.7 0 0 0 1.4 1.6 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.86 2.86-.06.06A1.7 1.7 0 0 0 19.3 8.1a1.7 1.7 0 0 0 .6 1 1.7 1.7 0 0 0 1.1.4h.1v4H21a1.7 1.7 0 0 0-1.6 1.4Z"/>')[name]||'<circle cx="12" cy="12" r="8"/>';return `<svg ${common}>${p}</svg>`}
function getState(){try{return window.AA_APP?.get?.('state')?.get?.()||null}catch(_){return null}}
function streak(days){let n=0,d=new Date();d.setHours(12,0,0,0);for(let i=0;i<366;i++){const k=dayKey(d.getTime());if(Number(days?.[k]?.attempts||0)>0){n++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return n}
function due(items){const now=Date.now();return Object.values(items||{}).reduce((n,x)=>n+(Number(x?.dueAt||0)>0&&Number(x.dueAt)<=now?1:0),0)}
function retention(items){const now=Date.now(),DAY=86400000,arr=Object.values(items||{}).filter(x=>Number(x?.lastReviewAt||0)>0);if(!arr.length)return {score:null,strong:0,mid:0,review:100};let a=0,b=0,c=0;for(const x of arr){const age=Math.max(0,(now-Number(x.lastReviewAt))/DAY),st=Math.max(.18,Number(x.stabilityDays||.5)),r=Math.exp(-age/st);if(r>=.85)a++;else if(r>=.65)b++;else c++}const t=arr.length,strong=Math.round(a/t*100),mid=Math.round(b/t*100),review=Math.max(0,100-strong-mid);return {score:Math.round((a+b)/t*100),strong,mid,review}}
function readiness(){const el=app.querySelector('.scoreRing b');const n=Number((el?.textContent||'').trim());return Number.isFinite(n)?Math.max(0,Math.min(100,n)):null}
function mission(){const title=app.querySelector('.missionTitle')?.textContent?.trim()||'おすすめ学習';return title.replace(/^今いちばん合格力に効く[：:]\s*/,'')}
function subjects(){const wanted=['英語','数学','国語','理科','社会'],rows=[];for(const r of app.querySelectorAll('.barLine')){const name=r.querySelector('label')?.textContent?.trim();if(!wanted.includes(name)||rows.some(x=>x.name===name))continue;const n=Number((r.querySelector('output')?.textContent||'').trim());rows.push({name,score:Number.isFinite(n)?Math.max(0,Math.min(100,n)):null})}return wanted.map(name=>rows.find(x=>x.name===name)||{name,score:null})}
function week(days){const out=[],d=new Date();d.setHours(12,0,0,0);for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);const v=days?.[dayKey(x.getTime())]||{};out.push({label:['日','月','火','水','木','金','土'][x.getDay()],minutes:Math.round(Number(v.ms||0)/60000)})}return out}
function chart(data){const W=560,H=118,max=Math.max(20,...data.map(x=>x.minutes)),pts=data.map((x,i)=>[10+i*90,H-14-(x.minutes/max)*88]),line=pts.map(p=>p.join(',')).join(' ');return `<div class="rv4Chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" aria-label="直近7日間の学習時間"><defs><linearGradient id="rv4line" x1="0" x2="1"><stop offset="0" stop-color="#78b8ff"/><stop offset=".55" stop-color="#a984ff"/><stop offset="1" stop-color="#f098cf"/></linearGradient></defs><line x1="10" y1="94" x2="550" y2="94"/><line x1="10" y1="56" x2="550" y2="56"/><polyline points="${line}"/></svg><div>${data.map(x=>`<span>${x.label}</span>`).join('')}</div></div>`}
function homeHTML(s){const today=s.stats?.days?.[dayKey()]||{},attempts=Number(today.attempts||0),accuracy=attempts?Math.round(Number(today.correct||0)/attempts*100):null,ready=readiness(),mem=retention(s.items),reviewDue=due(s.items),run=streak(s.stats?.days||{}),sub=subjects(),w=week(s.stats?.days||{}),weekMin=w.reduce((a,x)=>a+x.minutes,0);return `<section class="riseHomeV4"><header class="rv4Welcome"><div><span>RISE / LEARNING OS</span><h2>今日の一歩を、合格力に。</h2><p>${esc(fmtDate())} · ${attempts?`今日は${attempts}問演習済み`:'最優先の1つから始めよう'}</p></div></header><div class="rv4Metrics"><article class="rv4Card rv4Metric"><div class="rv4CardHead"><h3>旭丘 Readiness</h3><span>総合指標</span></div><div class="rv4MetricBody"><strong>${ready==null?'--':ready}</strong><small>/100</small><div class="rv4Ring" style="--v:${ready??0}"></div></div><p>${ready==null?'学習データを集めています':'現在の学習履歴から算出'}</p></article><article class="rv4Card rv4Metric"><div class="rv4CardHead"><h3>記憶の定着度</h3><span>現在</span></div><div class="rv4MetricBody"><strong>${mem.score==null?'--':mem.score}</strong><small>${mem.score==null?'':'%'}</small><div class="rv4Donut" style="--a:${mem.strong};--b:${mem.strong+mem.mid}"></div></div><div class="rv4Legend"><span><i></i>強い ${mem.strong}%</span><span><i></i>保持 ${mem.mid}%</span><span><i></i>復習 ${mem.review}%</span></div></article></div><div class="rv4MainGrid"><article class="rv4Card rv4Plan"><div class="rv4CardHead"><h3>今日の学習</h3><span>おすすめ</span></div><div class="rv4PlanRow"><b>優先</b><div><strong>${esc(mission())}</strong><span>現在の最優先課題</span></div><em>今</em></div><div class="rv4PlanRow"><b>復習</b><div><strong>${reviewDue?`復習待ち ${reviewDue}項目`:'復習はクリア'}</strong><span>忘却タイミングから選定</span></div><em>${reviewDue?'次':'✓'}</em></div><div class="rv4Actions"><button class="btn primary" data-action="start-mission">学習を開始</button><a class="btn ghost" href="./review/">復習を開く</a></div></article><article class="rv4Card"><div class="rv4CardHead"><h3>教科別達成度</h3><span>現在地</span></div><div class="rv4Subjects">${sub.map(x=>`<div><i>${subjectIcons[x.name]}</i><b>${x.name}</b><span><u style="width:${x.score??0}%"></u></span><em>${x.score==null?'--':x.score+'%'}</em></div>`).join('')}</div><div class="rv4Streak"><strong>${run}</strong><span>日連続学習</span></div></article><article class="rv4Card rv4Week"><div class="rv4CardHead"><h3>今週の学習</h3><span>直近7日</span></div><div class="rv4WeekTotal"><strong>${weekMin>=60?(weekMin/60).toFixed(1):weekMin}</strong><span>${weekMin>=60?'時間':'分'}</span><small>${accuracy==null?'正答率 未測定':`今日の正答率 ${accuracy}%`}</small></div>${chart(w)}</article></div></section>`}
function analyticsHTML(s){const ready=readiness(),w=week(s.stats?.days||{}),mins=w.reduce((a,x)=>a+x.minutes,0);return `<section class="riseAnalyticsV4"><div class="rv4PageTitle"><span>ANALYTICS</span><h2>学習分析</h2><p>正答率だけではなく、習熟・保持・回答速度・転移・測定信頼度を分けて確認します。</p></div><div class="rv4Metrics"><article class="rv4Card rv4Metric"><div class="rv4CardHead"><h3>旭丘 Readiness</h3><span>非公式指標</span></div><div class="rv4MetricBody"><strong>${ready==null?'--':ready}</strong><small>/100</small><div class="rv4Ring" style="--v:${ready??0}"></div></div></article><article class="rv4Card rv4Week"><div class="rv4CardHead"><h3>学習時間トレンド</h3><span>直近7日</span></div><div class="rv4WeekTotal"><strong>${mins>=60?(mins/60).toFixed(1):mins}</strong><span>${mins>=60?'時間':'分'}</span></div>${chart(w)}</article></div></section>`}
function decorateBrand(){const brand=app.querySelector('.brand');if(!brand)return;const mark=brand.querySelector('.mark'),h=brand.querySelector('h1'),p=brand.querySelector('p');if(mark)mark.textContent='R';if(h)h.textContent='Rise';if(p)p.textContent='旭丘合格のための学習OS'}
function decorateNav(){app.querySelectorAll('.nav button[data-route]').forEach(btn=>{const r=btn.dataset.route,m=routeMeta[r];if(!m)return;if(btn.dataset.riseV4==='1')return;btn.dataset.riseV4='1';btn.setAttribute('aria-label',m[0]);btn.innerHTML=`<b>${icon(m[1])}</b><span>${m[0]}</span>`})}
function decorateRoute(s){root.dataset.riseUi='2';root.dataset.riseSkin='v4';root.dataset.riseRoute=s.route||'home';decorateBrand();decorateNav();const main=app.querySelector('main');if(!main)return;if(s.route==='home'&&!main.querySelector('.riseHomeV4'))main.insertAdjacentHTML('afterbegin',homeHTML(s));if(s.route==='analytics'){const first=main.querySelector(':scope > section.card');if(first)first.classList.add('rv4LegacyLead');if(!main.querySelector('.riseAnalyticsV4'))main.insertAdjacentHTML('afterbegin',analyticsHTML(s))}}
let busy=false,raf=0;function run(){if(busy)return;busy=true;observer.disconnect();try{const s=getState();if(s)decorateRoute(s)}finally{busy=false;observer.observe(app,{childList:true,subtree:true})}}
const observer=new MutationObserver(()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(run)});observer.observe(app,{childList:true,subtree:true});requestAnimationFrame(run);addEventListener('pageshow',()=>requestAnimationFrame(run));
})();