(()=>{'use strict';
window.RISE_EXAM_MATH_FORMULAS={version:'1.2.0',updated:'2026-09-06',items:[
{id:'s01',cat:'geometry',tier:'speed',priority:'S',title:'相似比 → 面積比',formula:'相似比 a:b ⇒ 面積比 a²:b²',trigger:'相似な図形で、辺の比から面積を出したい',meaning:'長さがk倍なら面積はk²倍。面積を直接計算せず比だけで処理できる。',caution:'対応する辺・対応する面積をそろえる。'},
{id:'s02',cat:'solid',tier:'speed',priority:'S',title:'相似比 → 体積比',formula:'相似比 a:b ⇒ 体積比 a³:b³',trigger:'相似な立体で、辺の比から体積を出したい',meaning:'長さがk倍なら体積はk³倍。空間図形を大幅に短縮できる。',caution:'表面積比はk²、体積比はk³。'},
{id:'s03',cat:'geometry',tier:'speed',priority:'S',title:'直角三角形の整数比',formula:'3:4:5　／　5:12:13　／　7:24:25',trigger:'三平方を使う前に、3辺が有名な整数比の倍数かを見る',meaning:'平方根の計算をせず直角判定や未知辺を暗算で処理できる。',caution:'最大の数が斜辺。3辺すべて同じ倍率で拡大しても使える。'},
{id:'s04',cat:'geometry',tier:'speed',priority:'A',title:'45°-45°-90°',formula:'辺の比 1:1:√2',trigger:'直角二等辺三角形・正方形の対角線が見える',meaning:'三平方を展開せず斜辺・対角線を即決できる。',caution:'√2に対応するのは斜辺。'},
{id:'s05',cat:'geometry',tier:'speed',priority:'A',title:'30°-60°-90°',formula:'30°の向かい : 60°の向かい : 斜辺 = 1:√3:2',trigger:'正三角形を半分にした図、30°を含む直角三角形',meaning:'正三角形の高さや辺長を短時間で求められる。',caution:'一番短い辺は30°の向かい。'},
{id:'s06',cat:'geometry',tier:'speed',priority:'S',title:'斜辺への高さ 3公式',formula:'h²=pq　／　a²=c·p　／　b²=c·q',trigger:'直角三角形で直角頂点から斜辺へ高さを下ろした',meaning:'3つの直角三角形の相似を公式化。長さ問題を一気に処理できる。',caution:'cは元の斜辺、p,qは斜辺上の2区間。対応を図で確認する。'},
{id:'s07',cat:'geometry',tier:'speed',priority:'A',title:'角の二等分線定理',formula:'∠Aの二等分線AD ⇒ BD:DC = AB:AC',trigger:'三角形の頂点から角の二等分線が引かれている',meaning:'角度条件をそのまま辺の比へ変換できる。',caution:'BC上の比と、その両側の辺AB,ACを対応させる。'},
{id:'s08',cat:'geometry',tier:'speed',priority:'A',title:'内接円と三角形の面積',formula:'S=r·s　（s=(a+b+c)/2）',trigger:'三角形の内接円半径と周長・辺長が出ている',meaning:'内心から3辺へ高さrを下ろした3三角形の和。面積を速く出せる。',caution:'sは周長ではなく半周長。'},
{id:'s09',cat:'circle',tier:'speed',priority:'A',title:'同一点からの2接線',formula:'PA=PB',trigger:'円の外の同じ点Pから2本の接線が引かれている',meaning:'等辺を即発見し、二等辺三角形・合同へつなげられる。',caution:'A,Bが接点であること。'},
{id:'s10',cat:'coordinate',tier:'speed',priority:'A',title:'2点の中点',formula:'M((x₁+x₂)/2,(y₁+y₂)/2)',trigger:'座標上の線分の中点を直接求めたい',meaning:'x座標どうし、y座標どうしの平均だけで出せる。',caution:'xとyを混ぜない。'},
{id:'s11',cat:'coordinate',tier:'speed',priority:'A',title:'2点間の距離',formula:'AB=√{(x₂-x₁)²+(y₂-y₁)²}',trigger:'座標上の2点間の長さを求めたい',meaning:'三平方を座標にした形。関数×図形の検算にも使える。',caution:'xの差とyの差を別々に二乗する。'},
{id:'s12',cat:'coordinate',tier:'speed',priority:'S',title:'対称点で最短経路',formula:'折れ線PA+PBの最短 ⇒ 一方を基準線に関して対称移動し、一直線にする',trigger:'直線上を動く点Pを通る「2本の線分の和の最小」',meaning:'折れ線の最短を1本の直線距離へ変換する。関数×図形でも強い。',caution:'どの直線に関して対称移動するかを先に確認。'},
{id:'s13',cat:'coordinate',tier:'speed',priority:'A',title:'2点から直線の傾き',formula:'傾き=(y₂-y₁)/(x₂-x₁)',trigger:'2点だけ与えられて直線の式や変化の割合を出したい',meaning:'表やグラフを作らず傾きを直接求められる。',caution:'分母はxの差。x₂=x₁の垂直線では使えない。'},
{id:'s14',cat:'pattern',tier:'speed',priority:'A',title:'1からnまでの和',formula:'1+2+…+n=n(n+1)/2',trigger:'規則性・図形の個数・階段状の数え上げで1+2+…が出る',meaning:'長い足し算を1回の計算に変えられる。',caution:'1から連続する整数の和で使う。'},
{id:'s15',cat:'probability',tier:'speed',priority:'A',title:'余事象で「少なくとも」',formula:'P(少なくとも1回)=1-P(1回も起こらない)',trigger:'「少なくとも1回」「1個以上」を直接数えるのが面倒',meaning:'大量の場合分けを、起こらない側の計算へ反転できる。',caution:'補集合が本当に「1回も起こらない」になっているか確認。'},
{id:'s16',cat:'geometry',tier:'speed',priority:'S',title:'一角共有の面積比',formula:'同じ角θをはさむ2三角形 ⇒ S₁:S₂=(a·b):(c·d)',trigger:'2つの三角形が同じ角を共有し、その角をはさむ2辺の長さが分かる',meaning:'高さを作らず、共有角をはさむ辺の積だけで面積比を出せる。',caution:'比較する2辺は必ず「同じ角をはさむ2辺」。'},
{id:'s17',cat:'solid',tier:'speed',priority:'A',title:'直方体の対角線',formula:'d=√(a²+b²+c²)',trigger:'直方体の向かい合う頂点間の最短距離を求める',meaning:'三平方を2回書かず一式で空間対角線を求められる。',caution:'辺a,b,cが互いに直角である直方体の式。'},
{id:'a01',cat:'geometry',tier:'advanced',priority:'S',title:'チェバの定理',formula:'AD,BE,CFが1点で交わる ⇒ (BD/DC)×(CE/EA)×(AF/FB)=1',trigger:'三角形の3頂点から対辺へ引いた3本が一点に集まる',meaning:'3つの辺の比を一気につなぐ。難関図形で非常に強力。',caution:'目印は「3本が一点」。メネラウスの「3点が一直線」と区別する。'},
{id:'a02',cat:'geometry',tier:'advanced',priority:'S',title:'メネラウスの定理',formula:'D,E,Fが一直線 ⇒ (BD/DC)×(CE/EA)×(AF/FB)=1（長さの比）',trigger:'1本の直線が三角形の3辺またはその延長と交わる',meaning:'一直線条件を辺の比へ変換する。チェバとセットで強力。',caution:'外分を含む配置があるため、各線分の対応を図で丁寧に確認する。'},
{id:'a03',cat:'circle',tier:'advanced',priority:'S',title:'方べき（2本の割線・交わる弦）',formula:'PA×PB=PC×PD',trigger:'同じ点Pを通る2直線が同じ円とそれぞれ2点で交わる',meaning:'Pが円の内側でも外側でも、線分長を積だけで結べる。',caution:'同じ直線上の「Pから2交点まで」を1組として掛ける。'},
{id:'a04',cat:'circle',tier:'advanced',priority:'S',title:'方べき（接線×割線）',formula:'PT²=PA×PB',trigger:'円の外の点Pから接線PTと割線PABが出ている',meaning:'接線の長さと割線上の長さを直接結べる。',caution:'PTは接線、PAとPBは同じ割線上。'},
{id:'a05',cat:'circle',tier:'advanced',priority:'S',title:'トレミーの定理',formula:'円に内接する四角形ABCD ⇒ AC×BD=AB×CD+BC×DA',trigger:'4頂点が同じ円上にある四角形で、辺・対角線の長さが絡む',meaning:'内接四角形の長さ問題を一発で式にできる。',caution:'一般の四角形には使えない。「円に内接」が必須。'},
{id:'a06',cat:'geometry',tier:'advanced',priority:'A',title:'ヘロンの公式',formula:'s=(a+b+c)/2,　S=√{s(s-a)(s-b)(s-c)}',trigger:'三角形の3辺だけ分かっていて面積が必要',meaning:'高さを作らず3辺から面積を出せる。',caution:'計算が重い。特殊三角形や底辺×高さが簡単ならそちらを優先。'},
{id:'a07',cat:'geometry',tier:'advanced',priority:'A',title:'中線定理（アポロニウス）',formula:'辺aへの中線m ⇒ 4m²=2b²+2c²-a²',trigger:'三角形の中線と3辺の長さが絡む',meaning:'三平方を複数回使う処理を1式にまとめられる。',caution:'aは中線が向かう辺。'},
{id:'a08',cat:'geometry',tier:'advanced',priority:'A',title:'スチュワートの定理',formula:'BC=a=m+n, AD=d ⇒ b²m+c²n=a(d²+mn)',trigger:'三角形の頂点から対辺上の任意点へ引いた線分の長さを求めたい',meaning:'中線・角の二等分線など多くの線分公式を統一して扱える。',caution:'AB=c, AC=b, BD=m, DC=n の対応を崩さない。'},
{id:'a09',cat:'geometry',tier:'advanced',priority:'A',title:'角の二等分線の長さ',formula:'AD²=AB·AC-BD·DC',trigger:'角の二等分線ADそのものの長さを求めたい',meaning:'スチュワート＋角の二等分線定理を一式にした強力な時短形。',caution:'ADが本当に∠Aの二等分線であること。'},
{id:'a10',cat:'coordinate',tier:'advanced',priority:'A',title:'3点の座標から三角形の面積',formula:'S=|x₁(y₂-y₃)+x₂(y₃-y₁)+x₃(y₁-y₂)|/2',trigger:'原点を含まない3点の座標から面積を直接出したい',meaning:'底辺や高さを作らず座標だけで面積を求められる。',caution:'最後の絶対値を忘れない。'},
{id:'a11',cat:'coordinate',tier:'advanced',priority:'B',title:'三角形の重心座標',formula:'G((x₁+x₂+x₃)/3,(y₁+y₂+y₃)/3)',trigger:'座標上の三角形で3本の中線の交点を求めたい',meaning:'中線を2本立式して交点を求める作業を省ける。',caution:'3頂点のx座標・y座標をそれぞれ平均する。'},
{id:'a12',cat:'coordinate',tier:'advanced',priority:'A',title:'内分点の座標',formula:'AP:PB=m:n ⇒ P((nx₁+mx₂)/(m+n),(ny₁+my₂)/(m+n))',trigger:'線分ABを指定された比で分ける点の座標が必要',meaning:'比と座標を直接つなげられ、関数×図形で使いやすい。',caution:'係数は反対側の比を掛けると覚える。'},
{id:'a13',cat:'coordinate',tier:'advanced',priority:'B',title:'点と直線の距離',formula:'ax+by+c=0 と P(x₀,y₀) ⇒ d=|ax₀+by₀+c|/√(a²+b²)',trigger:'座標上で点から直線までの高さを直接求めたい',meaning:'垂線の式や交点を求めず距離を一発で出せる。',caution:'直線をax+by+c=0の形にそろえる。'},
{id:'a14',cat:'coordinate',tier:'advanced',priority:'B',title:'円の方程式',formula:'中心(a,b),半径r ⇒ (x-a)²+(y-b)²=r²',trigger:'座標上で円の中心・半径・円上の点をまとめて扱いたい',meaning:'円の条件を三平方の形で代数化できる。',caution:'中心の符号は式の中では反対になる。'},
{id:'a15',cat:'geometry',tier:'advanced',priority:'S',title:'余弦定理',formula:'a²=b²+c²-2bc cosA',trigger:'三角形で「2辺とその間の角」または「3辺」が分かる',meaning:'三平方を直角三角形以外へ拡張した公式。補助線なしで辺や角を求められる。',caution:'高校内容。角Aの向かいの辺がa。'},
{id:'a16',cat:'geometry',tier:'advanced',priority:'A',title:'正弦定理',formula:'a/sinA=b/sinB=c/sinC=2R',trigger:'三角形で辺とその向かいの角の組が1組以上分かる',meaning:'辺・角・外接円半径を直接つなげられる。',caution:'辺aと角Aのように「向かい合う組」を対応させる。'},
{id:'a17',cat:'geometry',tier:'advanced',priority:'A',title:'三角形の面積（2辺と角）',formula:'S=(1/2)ab sinC',trigger:'三角形の2辺とその間の角が分かっている',meaning:'高さを作らず面積を直接出せる。',caution:'Cは辺a,bにはさまれた角。'},
{id:'a18',cat:'circle',tier:'advanced',priority:'A',title:'直角三角形の外接円半径',formula:'R=斜辺/2',trigger:'直角三角形と外接円が同時に出る',meaning:'直角三角形の斜辺が外接円の直径になることを即利用できる。',caution:'直角三角形であることが前提。'},
{id:'a19',cat:'circle',tier:'advanced',priority:'B',title:'外接円半径と三角形の面積',formula:'R=abc/(4S)',trigger:'三角形の3辺と面積から外接円半径を出したい',meaning:'外心を作図したり正弦定理を展開せず半径を求められる。',caution:'a,b,cは三角形の3辺、Sは面積。'},
{id:'a20',cat:'circle',tier:'advanced',priority:'B',title:'ブラーマグプタの公式',formula:'円に内接する四角形 ⇒ S=√{(s-a)(s-b)(s-c)(s-d)}, s=(a+b+c+d)/2',trigger:'円に内接する四角形の4辺だけが分かり面積が必要',meaning:'対角線や高さを求めず4辺から面積を出せる。',caution:'一般の四角形では使えない。必ず円に内接していること。'},
{id:'a21',cat:'geometry',tier:'advanced',priority:'A',title:'正三角形の面積',formula:'S=(√3/4)a²',trigger:'正三角形の一辺だけ分かっていて面積が必要',meaning:'高さa√3/2を毎回出す手順を省ける。',caution:'正三角形限定。'},
{id:'a22',cat:'solid',tier:'advanced',priority:'A',title:'正四面体の高さ',formula:'h=(√6/3)a',trigger:'一辺aの正四面体の高さを求めたい',meaning:'底面の重心までの距離を作って三平方をする手順を省ける。',caution:'4面すべてが合同な正三角形の正四面体限定。'},
{id:'a23',cat:'solid',tier:'advanced',priority:'A',title:'正四面体の体積',formula:'V=(√2/12)a³',trigger:'一辺aの正四面体の体積を求めたい',meaning:'底面積と高さを別々に計算せず一式で出せる。',caution:'正四面体限定。'},
{id:'a24',cat:'geometry',tier:'advanced',priority:'B',title:'ブリティッシュ・フラッグ定理',formula:'長方形ABCDの任意点P ⇒ PA²+PC²=PB²+PD²',trigger:'長方形の内部・外部の点から4頂点への距離が複数出る',meaning:'未知の1距離を三平方の連続計算なしで求められる。',caution:'ABCDが長方形であること。Pの位置は内外どちらでもよい。'},
{id:'a25',cat:'geometry',tier:'advanced',priority:'B',title:'平行四辺形の法則',formula:'対角線p,q・隣辺a,b ⇒ p²+q²=2(a²+b²)',trigger:'平行四辺形の辺と対角線の長さが絡む',meaning:'2本の対角線を別々に三平方・余弦処理する手間を減らせる。',caution:'長方形だけでなく一般の平行四辺形で成立する。'},
{id:'a26',cat:'count',tier:'advanced',priority:'A',title:'組合せ nCr',formula:'nCr=n!/{r!(n-r)!}',trigger:'n個から順番を区別せずr個を選ぶ',meaning:'樹形図が大きくなる選び方を短く数えられる。',caution:'順番を区別する並べ方にはそのまま使わない。'},
{id:'a27',cat:'pattern',tier:'advanced',priority:'A',title:'等差数列',formula:'aₙ=a₁+(n-1)d　／　Sₙ=n(a₁+aₙ)/2',trigger:'規則性問題で一定の差で増減する数列が現れる',meaning:'n番目・最初からn番目までの合計を一気に式にできる。',caution:'差dが一定であることを先に確認する。'}
]};
if(typeof document!=='undefined'&&!window.RISE_EXAM_MATH_VISUALS){const s=document.createElement('script');s.src='./visuals.js?v=1.0.0';s.defer=true;document.head.appendChild(s)}
})();