(()=>{'use strict';
window.RISE_EXAM_MATH_FORMULAS={version:'1.0.0',updated:'2026-09-06',items:[
{id:'f01',cat:'geometry',tier:'core',priority:'S',title:'相似比 → 面積比',formula:'相似比 a:b ⇒ 面積比 a²:b²',trigger:'相似な2つの図形で、辺の比から面積を求めたいとき',meaning:'長さがk倍になると面積はk²倍。愛知県の関数×図形・平面図形で特に重要。',caution:'対応する辺・対応する面積をそろえる。',quiz:'相似比が2:3の三角形の面積比は？',answer:'4:9'},
{id:'f02',cat:'solid',tier:'core',priority:'S',title:'相似比 → 体積比',formula:'相似比 a:b ⇒ 体積比 a³:b³',trigger:'相似な立体で、辺の比から体積を求めたいとき',meaning:'長さがk倍になると体積はk³倍。空間図形の時短に使える。',caution:'表面積比はk²、体積比はk³。',quiz:'相似比が2:5の立体の体積比は？',answer:'8:125'},
{id:'f03',cat:'geometry',tier:'core',priority:'S',title:'3:4:5の直角三角形',formula:'3²+4²=5²',trigger:'直角三角形らしい図で辺の比が3・4・5の倍数になっているとき',meaning:'三平方を毎回計算せず直角・辺長を瞬時に確認できる。2026愛知県入試でも解法の鍵になった。',caution:'最大辺が5に対応する。比の倍数でも使える。',quiz:'辺が6,8,10の三角形は？',answer:'直角三角形'},
{id:'f04',cat:'geometry',tier:'core',priority:'A',title:'45°-45°-90°',formula:'辺の比 1:1:√2',trigger:'直角二等辺三角形を見つけたとき',meaning:'斜辺や対角線を一瞬で出せる。正方形の対角線にも直結。',caution:'√2に対応するのは斜辺。',quiz:'直角をはさむ2辺が5,5のとき斜辺は？',answer:'5√2'},
{id:'f05',cat:'geometry',tier:'core',priority:'A',title:'30°-60°-90°',formula:'30°の向かい : 60°の向かい : 斜辺 = 1:√3:2',trigger:'正三角形を半分にした図や30°を含む直角三角形',meaning:'正三角形の高さ・面積や角度付き図形を高速処理できる。',caution:'一番短い辺は30°の向かい。',quiz:'斜辺が10、30°の向かいの辺は？',answer:'5'},
{id:'f06',cat:'geometry',tier:'core',priority:'S',title:'直角三角形どうしの相似',formula:'直角が等しく、さらに1角が等しい ⇒ 2角相等で相似',trigger:'垂線・高さ・正方形・円の半径などで直角が複数できる図',meaning:'愛知の図形で頻出の見抜き方。比を作る入口になる。',caution:'「直角だから相似」だけでは不足。もう1角を確認。',quiz:'2つの直角三角形がもう1つ同じ角をもつとき何が言える？',answer:'相似'},
{id:'f07',cat:'geometry',tier:'core',priority:'A',title:'平行線と線分比',formula:'DE∥BC ⇒ AD:DB = AE:EC',trigger:'三角形の中に一辺と平行な線があるとき',meaning:'相似を作らず比だけ素早く取れる代表形。',caution:'どの辺が対応しているかを図で確認する。',quiz:'AD:DB=2:3、DE∥BCならAE:ECは？',answer:'2:3'},
{id:'f08',cat:'geometry',tier:'core',priority:'A',title:'中点連結定理',formula:'D,Eが2辺の中点 ⇒ DE∥BC かつ DE=BC/2',trigger:'三角形の2辺の中点を結ぶ線分があるとき',meaning:'平行・相似・長さを同時に得られる。空間図形の切断面にも強い。',caution:'2点とも中点であることを確認。',quiz:'BC=12のとき中点連結線DEは？',answer:'6'},
{id:'f09',cat:'geometry',tier:'speed',priority:'S',title:'直角三角形・斜辺への高さ',formula:'h²=pq',trigger:'直角頂点から斜辺へ垂線を下ろし、斜辺がp,qに分かれるとき',meaning:'3つの直角三角形の相似から出る時短公式。長さ問題に強い。',caution:'hは斜辺に下ろした高さ。p,qは斜辺上の2区間。',quiz:'p=4,q=9なら高さhは？',answer:'6'},
{id:'f10',cat:'geometry',tier:'speed',priority:'A',title:'角の二等分線定理',formula:'∠Aの二等分線AD ⇒ BD:DC = AB:AC',trigger:'三角形の頂点から角の二等分線が引かれているとき',meaning:'角度条件を辺の比へ変換できる。',caution:'分けられる辺BCの比と、両側の辺AB,ACを対応させる。',quiz:'AB:AC=3:5ならBD:DCは？',answer:'3:5'},
{id:'f11',cat:'geometry',tier:'advanced',priority:'A',title:'チェバの定理',formula:'AD,BE,CFが1点で交わる ⇒ (BD/DC)×(CE/EA)×(AF/FB)=1',trigger:'三角形の3頂点から対辺へ引いた3本の線が1点に集まる図',meaning:'複雑な比を一気につなげられる難関入試向け公式。',caution:'3本が「一点で交わる」配置。メネラウスと混同しない。',quiz:'チェバで3つの比を掛けた値は？',answer:'1'},
{id:'f12',cat:'geometry',tier:'advanced',priority:'A',title:'メネラウスの定理',formula:'一直線が三角形の3辺または延長を横切る ⇒ 比3つの積=1（長さの比で扱う形）',trigger:'1本の直線が三角形の3辺・延長上の3点を通る図',meaning:'一直線条件を辺の比へ変換する難関図形の強力な道具。',caution:'配置によって外分が入る。中学生向けには正の長さの比で図を確認して使う。',quiz:'メネラウスを使う目印は「3本が一点」か「3点が一直線」か？',answer:'3点が一直線'},
{id:'f13',cat:'circle',tier:'advanced',priority:'S',title:'方べきの定理（2本の割線）',formula:'PA×PB = PC×PD',trigger:'同じ点Pを通る2直線が円を横切るとき',meaning:'円の線分長を積で結べる。相似を毎回作るより速い。',caution:'Pから近い点・遠い点までの長さを同じ直線ごとに掛ける。',quiz:'PA=2,PB=8,PC=4ならPDは？',answer:'4'},
{id:'f14',cat:'circle',tier:'advanced',priority:'A',title:'方べき（接線×割線）',formula:'PT² = PA×PB',trigger:'円の外の点Pから接線PTと割線PABが引かれているとき',meaning:'接線の長さを積へ変換できる。',caution:'PTは接線部分。PA,PBは同じ割線上。',quiz:'PA=3,PB=12ならPTは？',answer:'6'},
{id:'f15',cat:'circle',tier:'core',priority:'A',title:'同じ点から引いた2本の接線',formula:'PA = PB',trigger:'円の外の同一点Pから2本の接線が引かれているとき',meaning:'等しい長さを即発見でき、合同・二等辺三角形へつながる。',caution:'A,Bがそれぞれ接点であること。',quiz:'同一点Pから円への接線PA,PBについて言えることは？',answer:'PA=PB'},
{id:'f16',cat:'circle',tier:'advanced',priority:'A',title:'トレミーの定理',formula:'円に内接する四角形ABCD ⇒ AC×BD = AB×CD + BC×DA',trigger:'4頂点が同じ円上にある四角形で辺・対角線の長さを求めるとき',meaning:'内接四角形の長さ問題を一発で式にできる。',caution:'円に内接していることが前提。一般の四角形には使えない。',quiz:'トレミーで「対角線の積」は何に等しい？',answer:'向かい合う辺の積2つの和'},
{id:'f17',cat:'geometry',tier:'advanced',priority:'B',title:'ヘロンの公式',formula:'s=(a+b+c)/2,  S=√{s(s-a)(s-b)(s-c)}',trigger:'三角形の3辺だけが分かり、面積が必要なとき',meaning:'高さを作らず3辺から面積を求められる。',caution:'計算量が大きいので、底辺×高さや特殊三角形が使えるならそちらを優先。',quiz:'3辺3,4,5の三角形の面積は？',answer:'6'},
{id:'f18',cat:'geometry',tier:'advanced',priority:'B',title:'中線定理（アポロニウス）',formula:'辺aへの中線m ⇒ 4m² = 2b²+2c²-a²',trigger:'三角形の中線と3辺の長さが絡むとき',meaning:'中線の長さを三平方の組合せなしで処理できる。',caution:'aは中線が引かれる先の辺。',quiz:'a=6,b=5,c=5のとき中線mは？',answer:'4'},
{id:'f19',cat:'geometry',tier:'speed',priority:'A',title:'内接円と面積',formula:'S = r×s  （s=(a+b+c)/2）',trigger:'三角形の内接円半径rと3辺・周長が絡むとき',meaning:'三角形を内心から3つに分けるとすぐ導ける。',caution:'sは周長ではなく半周長。',quiz:'半周長s=12、内接円半径r=2なら面積Sは？',answer:'24'},
{id:'f20',cat:'coordinate',tier:'speed',priority:'A',title:'2点の中点',formula:'M((x₁+x₂)/2, (y₁+y₂)/2)',trigger:'座標上で線分の中点を直接求めたいとき',meaning:'図形と関数の融合問題で時短になる。',caution:'xどうし、yどうしをそれぞれ平均する。',quiz:'A(2,4),B(8,10)の中点は？',answer:'(5,7)'},
{id:'f21',cat:'coordinate',tier:'speed',priority:'A',title:'2点間の距離',formula:'AB=√{(x₂-x₁)²+(y₂-y₁)²}',trigger:'座標上の2点間の長さを求めるとき',meaning:'三平方の定理を座標にした形。関数×図形の検算にも便利。',caution:'差の順番はどちらでもよいが、xとyを混ぜない。',quiz:'A(0,0),B(3,4)の距離は？',answer:'5'},
{id:'f22',cat:'coordinate',tier:'speed',priority:'S',title:'対称点で最短経路',formula:'折れ線PA+PBの最短 ⇒ 片方を直線に関して対称移動し、1本の直線にする',trigger:'ある直線上の点Pを通る2区間の長さの和を最小にしたいとき',meaning:'折れ線の最短を直線距離へ変える典型手法。2026愛知県の関数問題でも重要だった。',caution:'対称移動する対象と基準線を取り違えない。',quiz:'折れ線の長さを最小にする典型操作は？',answer:'一方の点を対称移動して直線にする'},
{id:'f23',cat:'coordinate',tier:'advanced',priority:'B',title:'座標三角形の面積（原点型）',formula:'O(0,0),A(x₁,y₁),B(x₂,y₂) ⇒ S=|x₁y₂-x₂y₁|/2',trigger:'原点と2点でできる三角形の面積を求めるとき',meaning:'高さを作らず座標だけで面積を出せる。',caution:'絶対値を忘れない。通常の底辺×高さで確認できるなら検算する。',quiz:'O,A(4,0),B(0,3)の面積は？',answer:'6'},
{id:'f24',cat:'count',tier:'advanced',priority:'B',title:'組合せ nCr',formula:'nCr = n! / {r!(n-r)!}',trigger:'n個から順番を区別せずr個を選ぶとき',meaning:'場合の数・確率で選び方を高速に数える高校式。',caution:'高校入試では表・樹形図の方が安全な場合も多い。順番を区別するなら使わない。',quiz:'5人から2人を選ぶ方法は？',answer:'10通り'}
]};
})();