(()=>{'use strict';
const VERSION='1.0.0',BANK=window.RISE_JAPANESE_CLASSICS_BANK_V1,STATE_KEY='kokugoChronologiaStateV2',PROGRESS_KEY='rise_kokugo_classics_progress_v1',WRONG_KEY='aa_kokugo_vocab_wrong_queue_v1';
if(!BANK||BANK.total!==1000)throw new Error('古文・漢文単語帳を初期化できません');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state=()=>{try{const x=JSON.parse(localStorage.getItem(STATE_KEY)||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return{}}},save=x=>{try{localStorage.setItem(STATE_KEY,JSON.stringify(x))}catch(_){}};
function wrongIds(){const out=new Set();try{const p=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}');for(const [id,x] of Object.entries(p||{}))if(x?.currentWrong===true||(x?.currentWrong==null&&(x?.wrong||0)>0&&(x?.wrong||0)>=(x?.correct||0)))out.add(id)}catch(_){}try{const rows=JSON.parse(localStorage.getItem(WRONG_KEY)||'[]');for(const x of Array.isArray(rows)?rows:[])if((x?.type==='koten'||x?.type==='kanbun')&&x.id)out.add(String(x.id))}catch(_){}return out}
let kind='all',view=[...BANK.all],page=0,covered=false,reviewOnly=false,shuffled=false;
const hira=s=>String(s||'').replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-96));
function domains(){const selected=$('#domain').value||'all',rows=kind==='all'?BANK.all:BANK[kind],values=[...new Set(rows.map(x=>x.area))];$('#domain').innerHTML='<option value="all">全分野</option>'+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(values.includes(selected))$('#domain').value=selected}
function levels(){const selected=$('#level').value||'all',rows=kind==='all'?BANK.all:BANK[kind],values=['S','A','B','C'].filter(level=>rows.some(x=>x.level===level)),labels={S:'S 最優先',A:'A 頻出',B:'B 重要・発展',C:'C 発展'};$('#level').innerHTML='<option value="all">全レベル</option>'+values.map(level=>`<option value="${level}">${labels[level]}</option>`).join('');if(values.includes(selected))$('#level').value=selected}
function stats(){const wrong=wrongIds();$('#totalCount').textContent=BANK.total.toLocaleString();$('#classicalCount').textContent=BANK.classical.length.toLocaleString();$('#kanbunCount').textContent=BANK.kanbun.length.toLocaleString();$('#reviewCount').textContent=BANK.all.filter(x=>wrong.has(x.id)).length.toLocaleString()}
function apply(resetPage=true){const q=$('#search').value.trim().toLowerCase(),domain=$('#domain').value,level=$('#level').value,sort=$('#sort').value,wrong=wrongIds();view=BANK.all.filter(x=>(kind==='all'||x.kind===kind)&&(domain==='all'||x.area===domain)&&(level==='all'||x.level===level)&&(!reviewOnly||wrong.has(x.id))&&(!q||(x.word+x.reading+x.meaning+x.area).toLowerCase().includes(q)));if(!shuffled)view.sort(sort==='kana'?(a,b)=>hira(a.reading||a.word).localeCompare(hira(b.reading||b.word),'ja'):(a,b)=>a.rank-b.rank);if(resetPage)page=0;render()}
function render(){stats();const per=Number($('#per').value)||50,max=Math.max(1,Math.ceil(view.length/per));page=Math.max(0,Math.min(page,max-1));const start=page*per,s=state(),part=view.slice(start,start+per);$('#rows').innerHTML=part.map(x=>`<article class="row"><div class="cell rank">#${x.rank}<small>${esc(x.displayBand)}</small></div><div class="cell word">${esc(x.word)}<span class="area">${esc(x.category)}・${esc(x.area)}</span></div><div class="cell reading">${esc(x.reading)}</div><div class="cell meaning ${covered?'covered':''}" tabindex="0" role="button" aria-label="意味を表示">${esc(x.meaning)}</div><div class="cell states"><button class="state ${s[x.id]==='learned'?'learned':''}" data-id="${x.id}" data-state="learned">覚えた</button><button class="state ${s[x.id]==='review'?'review':''}" data-id="${x.id}" data-state="review">要復習</button></div></article>`).join('')||'<div class="empty">条件に合う単語はありません。</div>';$('#status').textContent=`${view.length.toLocaleString()}語を表示対象にしています。意味を隠したときは、意味欄を押すと1語ずつ確認できます。`;$('#pager').innerHTML=`<button id="prev" ${page===0?'disabled':''}>前へ</button><span><input id="jump" type="number" min="1" max="${max}" value="${page+1}" inputmode="numeric" aria-label="ページ番号"> / ${max}</span><button id="next" ${page+1>=max?'disabled':''}>次へ</button>`;$('#prev').onclick=()=>{if(page){page--;render();scrollTo({top:0,behavior:'smooth'})}};$('#next').onclick=()=>{if(page+1<max){page++;render();scrollTo({top:0,behavior:'smooth'})}};const jump=$('#jump'),go=()=>{page=Math.max(0,Math.min(max-1,(parseInt(jump.value,10)||1)-1));render()};jump.onchange=go;jump.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();go()}}}
$('#rows').addEventListener('click',e=>{const button=e.target.closest('[data-state]');if(button){const s=state(),id=button.dataset.id,value=button.dataset.state;if(s[id]===value)delete s[id];else s[id]=value;save(s);render();return}const meaning=e.target.closest('.meaning.covered');if(meaning)meaning.classList.remove('covered')});$('#rows').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.meaning.covered')){e.preventDefault();e.target.classList.remove('covered')}});
$$('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;$$('[data-kind]').forEach(x=>x.classList.toggle('on',x===b));shuffled=false;domains();levels();apply()});['search','domain','level','sort','per'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{shuffled=false;apply()}));$('#toggleMeanings').onclick=()=>{covered=!covered;$('#toggleMeanings').textContent=covered?'意味を表示':'意味を隠す';$('#toggleMeanings').classList.toggle('on',covered);render()};$('#shuffle').onclick=()=>{shuffled=true;for(let i=view.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[view[i],view[j]]=[view[j],view[i]]}page=0;render()};$('#reviewOnly').onclick=()=>{reviewOnly=!reviewOnly;$('#reviewOnly').classList.toggle('on',reviewOnly);apply()};$('#reset').onclick=()=>{kind='all';$$('[data-kind]').forEach(x=>x.classList.toggle('on',x.dataset.kind==='all'));$('#search').value='';$('#sort').value='rank';reviewOnly=false;shuffled=false;covered=false;$('#reviewOnly').classList.remove('on');$('#toggleMeanings').classList.remove('on');$('#toggleMeanings').textContent='意味を隠す';domains();levels();apply()};
domains();levels();apply();document.documentElement.dataset.classicsVocab=VERSION;if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('../sw.js',{scope:'../'}).catch(()=>{});
})();
